### ISSUE TITLE
HTTPS Breaks it ?

### ISSUE THREAD

**Issue by Arnold0** [SmItH197/SteamAuthentication#100]
Hi,

After I do the login, then I'm redirected on the page, but insted of showing protected content, it shows content as if $_SESSION['steamid'] was still not set when going back on the page, but the login button disapear. Also the URL contains many parameters. If I reload the page, then protected content shows up fine (URL still shows many parameters). 
However if I'm testing it up on an other browser, using http instead of HTTPS then it works fine.

Is there some way to make it work correctly in HTTPS ?

Thanks

**Comment by bman46** [comment]
Pictures plz

**Comment by RedSparr0w** [comment]
I will test on my https server tonight and see if it works for me. I assume it's probably sorted due to no response in 2 months.

**Comment by bman46** [comment]
k

**Comment by Arnold0** [comment]
Actually ity's not because of HTTPS I was wrong. It works correctly in microsoft edge, but it doesn't on Google Chrome and in the Browser Integrated into Garry's mod game. In edge I don't need to reload the page after login, in the other two I need to do it.

I didn't post any new reply because I wrote on the page to reload it if the thing that needs login doesn't load.

In chrome, it actually shoots this error (I think I changed my PHP settings because I had no errors before) : Notice: A session had already been started - ignoring session_start() in /var/www/donate/steamauth/steamauth.php on line 37

**Comment by bman46** [comment]
odd, try getting the latest download of the library.

**Comment by Arnold0** [comment]
New version fixed it, nice !

**Comment by bman46** [comment]
--closed--
Fixed in new version
