### ISSUE TITLE
The login button not appear and stuck on "loading..."

### ISSUE THREAD

**Issue by Gicminos** [SmItH197/SteamAuthentication#101]
What did I do wrong?

**Comment by BlackCetha** [comment]
Probably nothing at all.
Try it again now, steam was probably down.

**Comment by Gicminos** [comment]
No, it's on loading too now

**Comment by Gicminos** [comment]
Not working now too... php problem?

**Comment by bman46** [comment]
Can you screenshot it

**Comment by bman46** [comment]
--Close--
due to no response
