### ISSUE TITLE
I need your help!

### ISSUE THREAD

**Issue by mtx** [SmItH197/SteamAuthentication#103]
Hello,
So I've started creating my website and i used a free host and a free domain, your SteamAuthentication worked great there , but as soon as i changed to a paid domain and host it stopped working. I have to mention that i changed the domain name and api key. I dont know what else to do. Every time I click on the login button it sends me to "domainname.com/?login" and it doesnt take me to the steam page.
I would be really gratefull if you could help me out.

**Comment by mtx** [comment]
I changed the require steamauth.php to the very first thing in my file and it seem to have fixed the problem. I still dont understand why it worked on my older host. Glad it works now.

**Comment by kekegod** [comment]
I have the exact same problem and my require steamauth.php was already at the very top. works fine at localhost, stays "domainname.com/?login" at web server.
