### ISSUE TITLE
Steam flag workaround?

### ISSUE THREAD

**Issue by danifantom** [SmItH197/SteamAuthentication#104]
Hello, I know this is not an "issue" itself but, my site got flagged by steam(just as csgodouble and others big sites did), I bought a new domain and new hosting for login purposes, now the flag is gone but I can't seem to redirect to the main site with the session variables, can You tell me how this is done?

**Comment by BlackCetha** [comment]
PHP uses cookies to assign sessions to users. Cookies are domain specific and will not be sent to any other site by the browser.

You can however use this workaround: [http://stackoverflow.com/a/19546680/4396938](http://stackoverflow.com/a/19546680/4396938)

**Comment by danifantom** [comment]
I wonder how the big sites managed to do it. They don't seem even to use the domain itself, but i tried it and it doesn't redirect if I don't use it

**Comment by BlackCetha** [comment]
- Close -

**Comment by bman46** [comment]
closed
