### ISSUE TITLE
User not logged in error in all browsers but chrome!

### ISSUE THREAD

**Issue by danifantom** [SmItH197/SteamAuthentication#105]
When I try to log in in my site through Steam i get the error "user is not logged in". But the strange thing is that this happens in firefox, edge, explorer, but not in chrome. Chrome is the only browser getting through the login. I have set API key correctly, and haven't changed any of the original code, just the API KEY.

**Comment by lopataz** [comment]
Hi! I have the same issue with some user

How did you resolve it?

regards
