### ISSUE TITLE
no login button

### ISSUE THREAD

**Issue by MrFraim** [SmItH197/SteamAuthentication#106]
Hi!
title says everything:
I uploaded the folder etc. and tried the steamauth with the demo.php but there's no login button.
http://mrfraim.de/media2/screen1.PNG demo from my view
http://mrfraim.de/media2/screen2.PNG folders & stuff
http://mrfraim.de/media2/screen3.PNG settings.php
Hope you can help me :)

**Comment by bman46** [comment]
can you put a screen shot of your demo.php page, that probably where you code is messed up.

**Comment by MrFraim** [comment]
https:/mrfraim.de/media2/screen4.PNG
I just copied the one from the Download Archive

**Comment by bman46** [comment]
Try removing the php code at the top of the settings page that requires the steamauth.php

**Comment by bman46** [comment]
At the top of the settings page

**Comment by MrFraim** [comment]
thank you works fine after removing the php code @ top of settings
