### ISSUE TITLE
It does not provide the appropriate values in the database It does not provide the appropriate values in the database $steamprofile['steamid']

### ISSUE THREAD

**Issue by trololo151** [SmItH197/SteamAuthentication#111]
$result = mysql_query("INSERT INTO SteamIdProfile VALUES ('$steamprofile[steamid]', '  $steamprofile[personaname]')");
instead of the desired parameter, it sends inexplicably one and same numbers 2147483647

**Comment by BlackCetha** [comment]
PHP will not replace arrays in strings as it does with normal variables.
You should try `'".$steamprofile["*"]."'`.

**Comment by trololo151** [comment]
I do not understand what you mean by that code. this does not work.

**Comment by SmItH197** [comment]
http://stackoverflow.com/questions/10255724/incorrect-integer-2147483647-is-inserted-into-mysql

Have you setup the I'd column as integer? Try changing it to varchar

**Comment by trololo151** [comment]
Excellent! It works. Thank you my friend!

**Comment by SmItH197** [comment]
No worries!
