### ISSUE TITLE
Openid issue?

### ISSUE THREAD

**Issue by FaBerTV** [SmItH197/SteamAuthentication#112]
Im trying the pure demo site to make sure it is working, but when you click the login button, the page loads for a long time.
https://gyazo.com/ef70adf94328c79aa330bbba9168ccfa

Then later the site show this message:
https://gyazo.com/03c83e2bf7e5e1a1d18b701d6a39141b

I dont really know what to do, as i already did the changes said at the main post.
Thanks in advance.

**Comment by BlackCetha** [comment]
https://github.com/SmItH197/SteamAuthentication/issues/90
Most likely your host blocking external requests.

**Comment by FaBerTV** [comment]
So should i try another host? Do you recommend any free one?

**Comment by FaBerTV** [comment]
Nice, i change my host, now it is working, thank you!! :dancers:
