### ISSUE TITLE
Users are logged out when browser session ends

### ISSUE THREAD

**Issue by Chuzzy** [SmItH197/SteamAuthentication#113]
How do you keep users logged in when the browser is closed? Do you have to store their profile id locally?

**Comment by BlackCetha** [comment]
This is just the regular PHP session system.
It stores the session data on your server and passes a cookie with a session-id to the client.
That cookie is set to expire when the browser is closed by default.

**Comment by bman46** [comment]
Maybe this will help http://stackoverflow.com/questions/1354999/keep-me-logged-in-the-best-approach
