### ISSUE TITLE
Clicked log-in button but nothing happens

### ISSUE THREAD

**Issue by mrjaviipr** [SmItH197/SteamAuthentication#114]
Hello. Im having this problem right now. When I click the login button, nothing happens except "?login" appears in my url (localhost). I edited everything with my info and folders name, etc.

Also, I made an AJAX to display the button with my login.php 

login.php

> <?php
> if(!isset($_SESSION['steamid'])) {
> 
>     echo "welcome guest! please login \n \n";
>     steamlogin(); //login button
>     
> }  else {
>     include_once ('includes/userInfo.php');
> 
>     //Protected content
>     echo "Welcome back " . $steamprofile['personaname'] . "</br>";
>     echo "here is your avatar: </br>" . '<img src="'.$steamprofile['avatarfull'].'" title="" alt="" />'; // Display their avatar!
>     
>     logoutbutton();
> }    
> ?>

**Comment by bman46** [comment]
Did u put the require steamauth at the top of the page? Also I would not change the file names within the steam folder or you may break it.

**Comment by mrjaviipr** [comment]
yes. sorry for not adding the complete code. 
I opened login.php and everything works fine. The problem might be the AJAX..

**Comment by bman46** [comment]
K

**Comment by bman46** [comment]
What file did u add the Ajax?

**Comment by mrjaviipr** [comment]
login.php

I want to display a Log In box with Steam and maybe facebook or twitter as options. After logging in, I want to display a contact form to add records to a mysql database. I implemented AJAX so everything appears without refreshing or redirecting to other pages. Im doing it wrong?

**Comment by bman46** [comment]
Hmm... I don't really have very much experience with other logins so I'll look into it but for the steam auth it just a button that u click on which direct u to a steam login page and then to the desired page specified in the setting. You may be able to recode the library so then it opens a pop up asking u to sign in but other that that I don't really know much more about it.

**Comment by bman46** [comment]
i don't think u can use ajax to stay on the login page while logging in, you have to go to the steam community website. I have never really seen a website that stays in one login page.

(if i a not understanding what u want to do correctly tell me, i am sort of inferring what u want to do)

**Comment by mrjaviipr** [comment]
That was my mistake. Thinking that using AJAX, the log in button was going to work normally. Thanks for your help . My bad.

**Comment by bman46** [comment]
K

**Comment by mrjaviipr** [comment]
After "log in", I receive an 404 error. 

> Not Found
> 
> HTTP Error 404. The requested resource is not found.

The page to redirect to after a successfull login is $steamauth['loginpage'] = "submit.php"; (submit.php is on the root directory)

**Comment by SmItH197** [comment]
What is the URL you are being redirected to?

**Comment by mrjaviipr** [comment]
`http://localhost/H1Z1%20Name%20Generator/submit.php?login&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198199060665&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198199060665&openid.return_to=http%3A%2F%2Flocalhost%2FH1Z1%2520Name%2520Generator%2Fsubmit.php%3Flogin&openid.response_nonce=2016-02-24T22%3A13%3A12ZDpsJQHqOH9A5exylmAkoYbxVL%2F8%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=LhBUCzSAajCvsys51MqBtEYCV4E%3D`

**Comment by bman46** [comment]
Try redownloading the steam auth files, if that does not work create a new issue because this one was closed.

**Comment by bman46** [comment]
An it would probably be a library issue of redownloading it does not work

**Comment by mrjaviipr** [comment]
ok thanks.

**Comment by bman46** [comment]
Did it work?

Sent from my iPhone
