### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by HeeysamH** [SmItH197/SteamAuthentication#118]
When im trying to login to my website http://hvs9.comxa.com/

it logs me in but it shows me this "No OpenID Server found at http://steamcommunity.com/openid/id/76561198009442049"

**Comment by SmItH197** [comment]
Could you create a new php file on your web host and put the following code in:

```php
<?php
if( ini_get('allow_url_fopen') ) {
   echo "enabled";
} else {
    echo "disabled";
}
?>
```
And visit it in your browser and tell me if it says enabled or disabled?

**Comment by SmItH197** [comment]
This issue has come up before, seems to be a hosting configuration issue. #54

**Comment by HeeysamH** [comment]
It says enabled

**Comment by HeeysamH** [comment]
It says Enabled

**Comment by RedSparr0w** [comment]
according to https://github.com/ztizzlegaming/CSGOWinBig/issues/9 its a problem with 000webhost

**Comment by HeeysamH** [comment]
kk thanks
