### ISSUE TITLE
User profile data issues

### ISSUE THREAD

**Issue by xevex7** [SmItH197/SteamAuthentication#119]
Hi all,

I am having an issue with the user data not being pulled in on the demo.php or example.php pages. I am able to click login, sign in, redirect back to the page. But the page itself doesnt display any info. I can load my api url itself and see the json response with all of the info in it. Ive been stuck on this problem for a long time now with no results.  Heres my test url: [http://skintopia.rip/test/example.php](http://skintopia.rip/test/example.php)

Any help on this would be greatly appreciated

**Comment by bman46** [comment]
code plz

**Comment by xevex7** [comment]
heres the php for the example page:

<?php
    require ('steamauth/steamauth.php');  
    
	# You would uncomment the line beneath to make it refresh the data every time the page is loaded
	 //$_SESSION['steam_uptodate'] = false;
?>
<html>
<head>
    <title>page</title>
</head>
<body>
<?php
if(!isset($_SESSION['steamid'])) {

    echo "welcome guest! please login \n \n";
    steamlogin(); //login button
    
}  else {
    include ('steamauth/userInfo.php');

    //Protected content
    echo "Welcome back " . $steamprofile['personaname'] . "</br>";
    echo "here is your avatar: </br>" . '<img src="'.$steamprofile['avatarfull'].'" title="" alt="" />'; // Display their avatar!
	$api = "http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=xxxxxxxxxxxxx&steamids=76561197987909074";

    
    logoutbutton();
}    
?>  
</body>
</html>

**Comment by xevex7** [comment]
I didnt touch any of the other files, other than the settings.php file.

**Comment by bman46** [comment]
k

**Comment by bman46** [comment]
whats this for?
`$api = "http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=xxxxxxxxxxxxx&steamids=76561197987909074";`

**Comment by xevex7** [comment]
it was for a test i was doing below that info, but nothing was working. I was attempting to get a direct response from the api url, but it was failing, so I got rid of the rest of the code.

**Comment by bman46** [comment]
do you have the latest version?

**Comment by xevex7** [comment]
It is the same, just omit the $api variable. 

<?php
    require ('steamauth/steamauth.php');  
    
	# You would uncomment the line beneath to make it refresh the data every time the page is loaded
	 //$_SESSION['steam_uptodate'] = false;
?>
<html>
<head>
    <title>page</title>
</head>
<body>
<?php
if(!isset($_SESSION['steamid'])) {

    echo "welcome guest! please login \n \n";
    steamlogin(); //login button
    
}  else {
    include ('steamauth/userInfo.php');

    //Protected content
    echo "Welcome back " . $steamprofile['personaname'] . "</br>";
    echo "here is your avatar: </br>" . '<img src="'.$steamprofile['avatarfull'].'" title="" alt="" />'; // Display their avatar!

    
    logoutbutton();
}    
?>  
</body>
</html>

**Comment by bman46** [comment]
k, try typing `http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=xxxxxxxxxxxxx&steamids=76561197987909074` directly into your browser (put the key in) and see if it returns something, if it does not it may be a steam issue

**Comment by xevex7** [comment]
it does return the json, that what I was trying to say in my original post. I can get the json response but when i attempt to parse the values and post them using the php code, it doesnt display anything. 

Heres the json response:
{
	"response": {
		"players": [
			{
				"steamid": "76561197987909074",
				"communityvisibilitystate": 3,
				"profilestate": 1,
				"personaname": "xe[V]ex",
				"lastlogoff": 1458062603,
				"profileurl": "http://steamcommunity.com/profiles/76561197987909074/",
				"avatar": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/3a/3afb493635a5f3c851675f10d3e9fab2b64c526e.jpg",
				"avatarmedium": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/3a/3afb493635a5f3c851675f10d3e9fab2b64c526e_medium.jpg",
				"avatarfull": "https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/3a/3afb493635a5f3c851675f10d3e9fab2b64c526e_full.jpg",
				"personastate": 1,
				"realname": "xxxxx",
				"primaryclanid": "103582791430012634",
				"timecreated": 1170195849,
				"personastateflags": 0,
				"loccountrycode": "US",
				"locstatecode": "CA",
				"loccityid": 387
			}
		]
		
	}
}

**Comment by bman46** [comment]
k

**Comment by bman46** [comment]
try the demo.php file

**Comment by bman46** [comment]
nvm tried it, same error

**Comment by bman46** [comment]
try re-downloading the steam auth folder

**Comment by xevex7** [comment]
I've done it several times :( , ill retry again though with a clean download. will test right now

**Comment by bman46** [comment]
k

**Comment by bman46** [comment]
what are the specs on your server, i saw that it took a few seconds to load you home page, it may not have enough power or RAM to run the steam API.

**Comment by bman46** [comment]
it also won't display images on your home page. But you website looks really nice btw.

**Comment by xevex7** [comment]
not entirely sure of the exact specs on my server, but i have a hosting account with ipage.com. not sure if that helps. Also, i reloaded the steam auth folder and replaced it on the server, but now my redirect leads to an incorrect URL. not sure what i broke now lol

**Comment by xevex7** [comment]
http://skintopia.rip/test/demo.php

**Comment by bman46** [comment]
if your having it hosted, check with ur host to see if they support the steam api.

**Comment by xevex7** [comment]
how would i go about checking if they support a specific api? would i just have to chat with someone from the company?

**Comment by bman46** [comment]
yes

**Comment by bman46** [comment]
ask if they support apis in general then ask if they support the steam api

**Comment by xevex7** [comment]
ok checking. thanks for all the help. this has been kicking my butt!

**Comment by bman46** [comment]
ikr

**Comment by RedSparr0w** [comment]
Have you tried enabling php error reporting to see what's going on? Also check your error logs

Sent from my iPhone

On 16/03/2016, at 1:35 pm, xevex7 <notifications@github.com<mailto:notifications@github.com>> wrote:


ok checking. thanks for all the help. this has been kicking my butt!

-

**Comment by xevex7** [comment]
I turned on error reporting and also had checked the error logs. I dont see any errors on either. 

www.skintopia.rip/test/example.php

I also re-uploaded the steam auth folder and fixed the settings file. I am still having the same issue. I am on with the tech support team for my hosting company, they are trying to help me solve this issue as well.

**Comment by bman46** [comment]
k

**Comment by RedSparr0w** [comment]
seems to be working for me now,
any idea what caused the problem?

**Comment by bman46** [comment]
I see that they have added  `example.php?login&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198068462075&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198068462075&openid.return_to=http%3A%2F%2Fskintopia.rip%2Ftest%2Fexample.php%3Flogin&openid.response_nonce=2016-03-16T21%3A07%3A37ZE2kzRpv%2BBppShBx3GGQUlFyN1ug%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=6xpcYS6uKAH43UWVOMKzGWmAems%3D` into the url

**Comment by RedSparr0w** [comment]
that shouldn't be staying in the url, it should redirect/reload when that stuff is there

**Comment by bman46** [comment]
Ik but it doesn't for some reason

**Comment by SmItH197** [comment]
It's not staying for me, I get redirected to example.php

**Comment by RedSparr0w** [comment]
im not getting it in the url either

**Comment by bman46** [comment]
for some reason it stays for me. Btw I'm running safari

**Comment by bman46** [comment]
i have tried manually reloading but it does not do anything

**Comment by bman46** [comment]
but when i go on the demo website bensmith.in (or something like that) it does not show that info there

**Comment by RedSparr0w** [comment]
are you going to this page http://skintopia.rip/test/example.php

**Comment by SmItH197** [comment]
Try the page in a private/incognito tab

**Comment by bman46** [comment]
its not doing it now for some reason

**Comment by RedSparr0w** [comment]
must have cached something somehow.

**Comment by bman46** [comment]
i think that they are editing the code, now when i leave the page it saves my login stuff.

**Comment by SmItH197** [comment]
That's normal

**Comment by bman46** [comment]
it was not earlier

**Comment by bman46** [comment]
weird

**Comment by RedSparr0w** [comment]
it should save your login info until you click logout or close the browser by default - (unless setup to remember for longer)

**Comment by bman46** [comment]
ik

**Comment by xevex7** [comment]
Yeah I have no idea what they did on their end to fix it, but the response i got is that they weren't seeing any server side errors or blocks. Yet, after talking to them its all the sudden working now lol. Im assuming they had the API being blocked for some reason, and fixed it. Thats the only conclusion I can come up with at this point. I appreciate all the help with this though guys! Thanks!

**Comment by SmItH197** [comment]
Glad to hear it, I will do some testing on ipage to see if I can find anything. Closed.
