### ISSUE TITLE
The issue with issues

### ISSUE THREAD

**Issue by BlackCetha** [SmItH197/SteamAuthentication#122]
I suggested a while back that we should add an explanation about the use of issues in the readme.
@SmItH197 said it wasnt really neccessary so i dropped the subject, but I wasnt really happy with it.

SteamAuthentication has always had this problem with new developers trying to get their first project running with a steam login.
Lets face it, around 80% of all downloads are for the "next big" CSGO gambling site. Many inexperienced developers try that as their first project because it seems relatively easy at first.

When they then run into problems like mysql-integration, they ask here without having done any research. That is not accepted on any programing platform/forum (SO and the like) and why should we provide support for people that are not even willing to read through the closed issue list?

For that matter, I think we should indeed include a warning about off-topic issues getting closed.
And, if possible, someone more active should get the rights to close said issues.

**Comment by Gummibeer** [comment]
I'm 100% with it - it's just annoying to get all the "how to use my brain" issues in my notifications instead of real issues. https://github.com/SmItH197/SteamAuthentication/issues/121#issuecomment-200257375

I'm willed to help guys to learn php and so on, but for that there are other places that are made for this reason like forums, chats or real-life meetups.

**Comment by SmItH197** [comment]
See my response on #121, I'll come up with something this week.

**Comment by RedSparr0w** [comment]
unfortunately i think no matter what comments are in the read me people will still continue to create "issues" based on not knowing how to use php/sql.

i agree someone else should also be granted the rights to close/label threads & in the readme a warning about off topic issues being closed

also im fairly sure i read somewhere recently that they are going to be shutting down csgo gambling sites (also EZSkins announced they are shutting down) which should help minimize these sorts of problems - don't quote me on it though [=

**Comment by SmItH197** [comment]
I'm having to do a lot of overtime at work at the moment as it's tax year end, I have a long weekend this week so I will be posting a few commits and tidying everything up and hopefully finishing the new example/demo site.

I've tidied up a lot of the issues, but will get round to the pull requests and commits on Friday. Thanks for your help with everything everyone, much appreciated! :)

**Comment by bman46** [comment]
you should just add a "general php" tag to bad questions and give more people rights to close it

**Comment by SmItH197** [comment]
Just merged #133, the number of crappy issues has definitely dropped off recently. I have created a new issues tag called "General PHP Query" and will be much more proactive with shutting down these kind of issues.

I will also close issues if the requester is using this library for gambling sites (Although it is up to them to disclose that - see #147.
