### ISSUE TITLE
Can't sign in with steam.

### ISSUE THREAD

**Issue by jonnytothedee** [SmItH197/SteamAuthentication#123]
Can anyone help me? I have no idea why my sign in isn't working properly.
http://www.csgo-crazy.com
It seems to work for some people, but it doesn't work on my end.
Any advice is greatly appreciated.
I will be on standby ALL day. Just ask for any files you need to see.

**Comment by SmItH197** [comment]
Works for me, what errors are you getting?

**Comment by jonnytothedee** [comment]
When I sign in, it takes forever to load, and when it finally does, it's an old version of my website that doesn't exist anymore. Then on that page in small text it says: No OpenID Server found at http://steamcommunity.com/openid/id/76561198157507254

**Comment by jonnytothedee** [comment]
My site is supposed to look like this:
![image](https://cloud.githubusercontent.com/assets/16887976/14028296/0662e042-f1b9-11e5-8a33-7ad8c04385b3.png)

After signing in it looks like this:

![image](https://cloud.githubusercontent.com/assets/16887976/14028290/fbb5e7ac-f1b8-11e5-9b41-63a27232f750.png)

**Comment by lithium720** [comment]
When I logged in all I ended up with was a MySQL error: [https://lithi.io/i/cc.jpg](url)

**Comment by lithium720** [comment]
I got a MySQL error when I tried it: [Image](https://lithi.io/i/cc.jpg)

**Comment by SmItH197** [comment]
I would recommend setting the login variable to index.php in settings.php as I'm not getting redirected properly to the home page, I get the same screen @lithium720 but if I then visit index.php im logged in

**Comment by jonnytothedee** [comment]
I already had my settings.php set to this:

<?php
$steamauth['apikey'] = "XXXXXXXXXXXXXXXXXXXXXXX"; // Your Steam WebAPI-Key found at http://steamcommunity.com/dev/apikey
$steamauth['domainname'] = "csgo-crazy.com"; // The main URL of your website displayed in the login page
$steamauth['logoutpage'] = "logout.php"; // Page to redirect to after a successfull logout (from the directory the SteamAuth-folder is located in) - NO slash at the beginning!
$steamauth['loginpage'] = "index.php"; // Page to redirect to after a successfull login (from the directory the SteamAuth-folder is located in) - NO slash at the beginning!
?>

**Comment by SmItH197** [comment]
@jonnytothedee try logging in incognito mode, if that works clear your cache.

**Comment by jonnytothedee** [comment]
For me even incognito mode brought me to that version of my website that doesn't exist anymore.
It takes an incredibly long time to load and then it just goes to that page:
![image](https://cloud.githubusercontent.com/assets/16887976/14028597/9862e126-f1ba-11e5-900a-40d54eae40be.png)

I'm about to blow my brains out.
maybe I need to edit this link? : https://steamcommunity.com/openid/login?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=checkid_setup&openid.return_to=http%3A%2F%2Fcsgo-crazy.com%2F%3Flogin&openid.realm=http%3A%2F%2Fcsgo-crazy.com&openid.ns.sreg=http%3A%2F%2Fopenid.net%2Fextensions%2Fsreg%2F1.1&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select

But I can't find it in any of my files.
I just don't get it. 
Apparently it only happens on my end.

**Comment by jonnytothedee** [comment]
Yeah no matter what account I try to sign in with on my end it just says: No OpenID Server found at http://steamcommunity.com/openid/id/76561198044225500

76561198044225500
is one of my old accounts steam ID

**Comment by lithium720** [comment]
Who do you host with? If I had to guess I would say this is a host configuration issue.
If you're being directed to "a version that doesn't exist anymore" then there is some very obvious server side caching or cache-control issues.

**Comment by jonnytothedee** [comment]
I host the site actually completely on my own. 
It's hosted via a virtual linux machine I have running apache2.

**Comment by lithium720** [comment]
Are you doing any weird page rules or .htaccess hacks?

**Comment by jonnytothedee** [comment]
No it's an incredibly straightforward setup.
![image](https://cloud.githubusercontent.com/assets/16887976/14031724/728f636e-f1cb-11e5-8810-d15c168eec01.png)

**Comment by lithium720** [comment]
Strange. It looks like it's just not redirecting to index.php correctly for some reason.

**Comment by SmItH197** [comment]
#83 seemed to have the same problem

**Comment by lithium720** [comment]
It also works if you just stuff /index.php into the URL string.
`http://csgo-crazy.com/index.php?login&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198018288710&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198018288710&openid.return_to=http%3A%2F%2Fcsgo-crazy.com%2F%3Flogin&openid.response_nonce=2016-03-24T21%3A30%3A49ZkNmPSpgSDH956I99goPAVdqiBWw%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=ppp7dd3MMd%2FqV4OMJidoi3csyzU%3D`

**Comment by BlackCetha** [comment]
This seems to be a redirection problem. As you can see in the login-url it tells steam to send you back to `/login`, wich is a 404 if you try to access it directly.
Based on your settings, I don't have any clue where that URL might come from.

As a cheap fix, you could create a directory called `login` in your webroot and place a index.php file in there that just redirects to your main page.

If I had to guess, something is messing with the GET-Parameter that is used by SteamAuthentication internally to start a login redirect. Maybe Steam went from stripping GET-Parameters completely from return-urls to appending them as subfolders? Very unlikely, but we are used to some strange stuff from valves side.

**Comment by jonnytothedee** [comment]
As you can see I added a directory called login:
![image](https://cloud.githubusercontent.com/assets/16887976/14034158/e6345e98-f1dd-11e5-921c-9652cadeaf99.png)
with the login.php inside 
![image](https://cloud.githubusercontent.com/assets/16887976/14034164/f61fb0aa-f1dd-11e5-8706-95055de6dcde.png)
But the sign in is still bringing me here: 
![image](https://cloud.githubusercontent.com/assets/16887976/14034172/02b26132-f1de-11e5-9264-23ae322b07d5.png)

I never thought it would be this hard to get my sign in to work.
It's aggravating me beyond belief because I know it's probably something so small somewhere.
But no one I know in real life knows coding at all so I have no fresh pair of eyes to look over everything.

**Comment by jonnytothedee** [comment]
Thank ALL of you so much for everything you've told me so far. I really appreciate it.
I never expected so many people to try and help me. <3

**Comment by lithium720** [comment]
@jonnytothedee Of course.

I have actually just recieved the really long GET string in my URL like you do when its not working, and it failed to log me in. I have not touched my index.php for days, while it has worked flawlessly for awhile now; however it has failed on me twice now in the last 20 minutes of signing in with different accounts. I end up with:

`https://lithi.io/?login&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198018288710&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198018288710&openid.return_to=https%3A%2F%2Flithi.io%2F%3Flogin&openid.response_nonce=2016-03-24T23%3A30%3A58ZuBJfz%2Fsk1NZhYnWveSlfWp58ehY%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=GGrscbr7OTpFqB5JSt6hj8Dey6U%3D`

**Comment by jonnytothedee** [comment]
Update. When I go to my site via the IP of my virtual machine I get this:
![1](https://cloud.githubusercontent.com/assets/16887976/14037469/876ad170-f201-11e5-880f-b035418948c2.png)
And when I log in it actually seems to work:
![image](https://cloud.githubusercontent.com/assets/16887976/14037475/93a292de-f201-11e5-90de-750ca9c8bf62.png)
![image](https://cloud.githubusercontent.com/assets/16887976/14037478/98c15f20-f201-11e5-8f72-d2b2384ae26b.png)
It's fast too it works seemingly perfectly.
The issue is I HAVE to access it via the IP of the hosting machine.
And it seems like the database doesn't record ANY of the information about me signing in.

I hope this information is enough for somebody to be able to help!

**Comment by BlackCetha** [comment]
When I try to log in, I get this: 
![MySQL error](https://cloud.githubusercontent.com/assets/7271868/14041852/0f82e3e0-f275-11e5-8432-767ca73678d0.png)

**Comment by RedSparr0w** [comment]
When I login I get directed to a the same page as above but no MySQL errors, to me it looks like you have another settings.php file somewhere in your root directory.

Main reason is because it does not redirect you correctly and you show your settings file is filled in correctly. Also when your goto the real homepage after logging in there is no display picture or name or anything anywhere because it can't load your information due to not being able to use your Api key. 

Make sure there is no other settings.php file anywhere and let us know if that fixes it

**Comment by RedSparr0w** [comment]
try enabling php error reporting and see if it shows anything.
i was getting the redirection problem due to 
`Warning: Cannot modify header information - headers already sent`

**Comment by jonnytothedee** [comment]
Do I need to only check my filezilla html folder for  extra settings.php?
Or my entire computer?
Also I found this folder.
It's just  called admin.
![image](https://cloud.githubusercontent.com/assets/16887976/14049306/acaf51b6-f271-11e5-9184-6a520fb3583f.png)

Could this be possibly messing up my site?

I'm not 100% sure how to enable php error reporting. :c

**Comment by jonnytothedee** [comment]
Deleting the admin folder seemingly did nothing.
![image](https://cloud.githubusercontent.com/assets/16887976/14049757/89309bde-f274-11e5-8591-3f930bb2b855.png)

**Comment by jonnytothedee** [comment]
Changed my openid settings file to this as well:
<?php

$apiKey = ['XXXXXXXXXXXXXXXXXXXXXXXXX'];
$steamauth['apikey'] = $apiKey; // Your Steam WebAPI-Key found at http://steamcommunity.com/dev/apikey
$steamauth['domainname'] = "http://www.csgo-crazy.com"; // The main URL of your website displayed in the login page
$steamauth['buttonstyle'] = "large_no"; // Style of the login button [small|large_no|large]
$steamauth['logoutpage'] = "index.php"; // Page to redirect to after a successfull logout (from the directory the SteamAuth-folder is located in) - NO slash at the beginning!
$steamauth['loginpage'] = "index.php"; // Page to redirect to after a successfull login (from the directory the SteamAuth-folder is located in) - NO slash at the beginning!
// System stuff
if (empty($steamauth['apikey'])) {die("<div style='display: block; width: 100%; background-color: red; text-align: center;'>SteamAuth:<br>Please supply an API-Key!</div>");}
if (empty($steamauth['domainname'])) {$steamauth['domainname'] = "localhost";}
if ($steamauth['buttonstyle'] != "small" and $steamauth['buttonstyle'] != "large") {$steamauth['buttonstyle'] = "large_no";}
?>

**Comment by BlackCetha** [comment]
Is your API-Key really formatted like this with the brackets around?

**Comment by SmItH197** [comment]
Can you post your index.php file up to and including the login function?

**Comment by SmItH197** [comment]
Its strange that it redirects perfectly if I visit the IP of your server, but doesn't if I use your domain name to access the website.

**Comment by SmItH197** [comment]
Do the EN/RU Links set any header/session info?

**Comment by lithium720** [comment]
To report all errors in php you can stuff `error_reporting(E_ALL);` Right after the first <?php opening.

**Comment by SmItH197** [comment]
whats in your .htaccess file?

**Comment by jonnytothedee** [comment]
I'm incredibly sorry about the late response, I was out eating lunch.

@BlackCetha my API key isn't actually X's, it's my actual API key if that's what you're asking, but yes it has brackets around it.

@SmItH197 My index.php file is:
<?php
@include_once "langdoc.php";
if(!isset($_COOKIE['lang'])) {
	setcookie("lang","ru",2147485547);
	$lang = "ru";
} else $lang = $_COOKIE["lang"];
$sitename = "CSGO-Crazy.com";
$title = "$sitename";
@include_once('set.php');
require('steamauth/steamauth.php');
	if(isset($_SESSION["steamid"])) {
include_once('steamauth/userInfo.php');}


$lastgame = fetchinfo("value","info","name","current_game");
$lastwinner = fetchinfo("userid","games","id",$lastgame-1);
$winnercost = fetchinfo("cost","games","id",$lastgame-1);
$winnerpercent = round(fetchinfo("percent","games","id",$lastgame-1),1);
$winneravatar = fetchinfo("avatar","users","steamid",$lastwinner);
$winnername = fetchinfo("name","users","steamid",$lastwinner);
$mytrade = fetchinfo("tlink","users","steamid",$_SESSION["steamid"]);
?>



<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title><?php echo $title ?></title>
	<meta name="keywords" content="FILL KEYWORD">
	<meta name="description" content="Welcome to CSGO-Crazy.com! Bet your CS:GO items in a small pot for your chance to win it all!"> 
	<link rel="stylesheet" href="css/style.css">
	<link rel="SHORTCUT ICON" href="favicon.ico">
	<script src="js/libs/jquery-2.1.3.min.js"></script>
	<script src="js/libs/jquery-ui.min.js"></script>
	<script src="js/jquery.noty.packaged.min.js"></script>
	<script src="js/jquery.cookie.js"></script>
	<script src="js/libs/jquery.arcticmodal-0.3.min.js"></script>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
	<script src="js/script.js"></script>
    <script type="text/javascript" src="chat/chat.js"></script>
	<link rel="stylesheet" href="chat/chat.css" type="text/css" />
    <script type="text/javascript">
    
        // ask user for name with popup prompt    
        var name = "<?php echo $steamprofile['personaname'] ?>";
		var ava = "<?php echo $steamprofile['avatarfull'] ?>";
    	
    	// display name on page
    	$("#name-area").html("You are: <span>" + name + "</span>");
    	
    	// kick off chat
        var chat =  new Chat();
    	$(function() {
    	
    		 chat.getState(); 
    		 
    		 // watch textarea for key presses
             $("#sendie").keydown(function(event) {  
             
                 var key = event.which;  
           
                 //all keys including return.  
                 if (key >= 33) {
                   
                     var maxLength = 57;  
                     var length = this.value.length;  
                     
                     // don't allow new content if length is maxed out
                     if (length >= maxLength) {  
                         event.preventDefault();  
                     }  
                  }  
    		 																																																});
    		 // watch textarea for release of key press
    		 $('#sendie').keyup(function(e) {	
    		 					 
    			  if (e.keyCode == 13) { 
    			  
                    var text = $(this).val();
    				var maxLength = $(this).attr("maxlength");  
                    var length = text.length; 
                     
                    // send 
                    if (length <= maxLength + 1) { 
                     
    			        chat.send(text, name, ava);	
    			        $(this).val("");
    			        
                    } else {
                    
    					$(this).val(text.substring(0, maxLength));
    					
    				}	
    				
    				
    			  }
             });
            
    	});
    </script>
</head>

<body class="ezpz-currency-ru"  onload="setInterval('chat.update()', 1000)">

<div class="chat" style="height: auto; z-index: 1000;">
  <header>
    <h2 class="title"><a>Chat</a></h2>
    <ul class="tools"><li><a class="fa fa-minus closech" >↑</a> <a class="fa fa-minus closechs hidden" >↓</a></li></ul>
  </header>
	<div id="page-wrap" class="hjgf hidden">
        <p id="name-area"></p>
        <div id="chat-wrap"><div id="chat-area"><?php include "chat.php";?></div></div>
		<?php
						if(!isset($_SESSION["steamid"])){
						echo '<div id="otpsoob"><div style="padding-top: 7px;">
									<a class="ezpz-loginas" style="font-size: 12px;border: 2px solid #db073d;margin: auto;padding-top: 12px;width: 230;min-height: 30px;height: 45;" href="/?login">CHANGE LOGIN</a>
								</div></div>';
						} else {
						echo '<div id="otpsoob"><form id="send-message-area">
								<textarea id="sendie" maxlength = "100" placeholder="ENTER SOMETHING"></textarea>
								</form></div>';
						}
						?>
    </div>
</div>



<div class="wrapper">
		<header class="header">
			<div class="header-inside clearfix">
				<a href="index.php" class="logo"><img src="css/img/icon-logo.png" height="45" width="215" alt=""></a>
				<ul class="clearfix">                        
					<li><a href="index.php">Home</a></li>
					<li><a href="support.php">Support</a></li>
					<li><a href="about.php">About</a></li>
				</ul>
				<ul class="clearfix">                                                
					<li><a href="history.php">History</a></li>
					<li><a href="rls.php">Rules</a></li>
					<li><a href="top.php">Top</a></li>
				</ul>
			</div>
		</header>
		<section class="after-header">
			<section class="after-header-language"><a href="ru.php">RU</a> | <a href="en.php">EN</a></section>
			<section class="after-header-inside"> 
				<article class="item clearfix">
					<ul class="stat clearfix">            
						<li>
							<h6 class="selector-online-users"><?php include 'online.php';?></h6>
							<p>Players Online</p>
						</li>
						<li>
							<h6 class="selector-stat-today-matches"><?php
											$result = mysql_query("SELECT id FROM games WHERE `starttime` > ".(time()-86400));
											echo mysql_num_rows($result);
										?></h6>
							<p>Games Today</p>
						</li>
						<li>
							<h6 class="selector-stat-today-players"><?php
										$row = mysql_fetch_array($result);
										$pls = 0;
										$itms = 0;
										for($i=$row["id"]; $i <= $lastgame; $i++) {
											$rst = mysql_query("SELECT id FROM game".$i." GROUP BY userid");
											$pls += mysql_num_rows($rst);
										}
										echo $pls;
										?></h6>
							<p>Players Today</p>
						</li>
						<li>
						<?php 
						$result = mysql_query("SELECT MAX(cost) AS cost FROM games");
						$row = mysql_fetch_assoc($result);
						$maxcost =  $row["cost"];
						?>
							<h6 class="selector-stat-max-sum" id="inf10"><?php echo round($maxcost,2); ?><span class="ezpz-price"></h6>
							<p>Highest Pot</p>
						</li>
					</ul>
					<?php
					if(!isset($_SESSION["steamid"])) {
						steamlogin();
						echo '<a class="ezpz-loginas" style="font-size: 12px;border: 2px solid #db073d;margin: 60px auto 0px;padding-top: 22px;" href="/?login">Login</a>';
							} else {
						echo '<article class="jfrs clearfix">
							<img src="'.$steamprofile['avatarfull'].'" height="74" width="74" alt="">
							<p>'.$steamprofile['personaname'].' <a href="steamauth/logout.php">Logout</a></p>
							<ul class="clearfix">
								<li><a href="http://steamcommunity.com/id/me/tradeoffers/privacy#trade_offer_access_url" target="_blank">Click to get Trade Url.</a></li>
							</ul>
						</article>
						
						<div class="buy">
							<p>Add to your nickname and win

bonus to win 5%!</p>
							<h6>CSGO-Crazy.com</h6>
						</div>
						
						<form method="POST" action="./updatelink.php">
						<input type="text" class="main-link" name="link" id="link" value="'.$mytrade.'" placeholder="Paste Trade Link ...">
						<input type="submit" class="main-link-check" href="#" value="">
						</form>';
						mysql_query("UPDATE users SET name='".$steamprofile['personaname']."', avatar='".$steamprofile['avatarfull']."' WHERE steamid='".$_SESSION["steamid"]."'");
					}
					?>
				</article>
			</section> 
		</section>

		
	<div class="selector-current-match">
	<section class="game">
		<a id="soundbut" class="sound-link sound-link-on"><i class="fa fa-volume-up"></i> Sound Off</a>
        <a id="soundbut" class="sound-link sound-link-off hidden"><i class="fa fa-volume-up"></i> Enable Sound</a>
		<h5>Game #<span class="selector-current-match-id"><?php echo $lastgame; ?></span></h5>
		<p>Current Pot: <span><span class="selector-current-match-prizepool" id="money_round">0</span><span class="ezpz-price"></span></span></p>
	</section> 
	<div class="progress" style="margin: auto;">
		<section class="progress-line"> 
			<div class="selector-items-progress-text number-itms" style="left: 0px;">
				<span class="selector-items-counter">0</span>
				<p>ITEMS</p>
			</div>
			<div class="line clearfix">
				<div class="blue-line">
					<div class="selector-items-progress red-line" id="meter" aria-valuemax="100" style="width: 0;"></div>
				</div>
				<a href="javascript:;" class="tooltip3 tooltip-effect-1">
					?
					<span class="tooltip-content3 clearfix">
						<span class="tooltip-text3">
							The game ends immediately ends if it reaches 100 items.
						</span>
					</span>
				</a>
			</div>
			<div class="until-end">
				<p>before the end of the game:</p>
				 								<span class="selector-timer" id="timeleft">0</span>
			</div>
		</section> 
		<div class="chance clearfix"> 
				<div class="your-chances-notlogged clearfix investments">
				<?php
						if(!isset($_SESSION["steamid"])){
						echo '<p style="font-size: 16px;">The Higher Dollar ammount of skins you insert<br> The higher your percentage at the pot.</p>';
						echo '<p style="font-size: 16px;">Maximum deposit - 10 items<br> Minimum deposit - 0.03<span class="ezpz-price"></span></p>';
						} else {
						echo '<p>You put in GAME <span style="font-size: 20px;color: #8ec7d2;"><span style="font-size: 20px;color: #8ec7d2;" class="selector-depositor-items-counter" id="myitem">0</span> ITEMS</span></p>';
						echo '<p>YOUR CHANCE TO WIN: <span style="font-size: 20px;color: #8ec7d2;" class="selector-depositor-chance" id="mychance">0%</span></p>';
						echo '<p>Minimum deposit 0.03$. Maximum deposit - 10 items</p>';
						}
						?>
				</div>
				<?php
						if(!isset($_SESSION["steamid"])) echo '<a href="/?login">Feeling lucky, punk?</a>';
						else {
							$token = fetchinfo("tlink","users","steamid",$_SESSION["steamid"]);
							if(strlen($token) < 2) echo '<button onclick="alert2(\'Enter a link to share in the settings!\')">Submit Items</button>';
							else echo '<a href="https://steamcommunity.com/tradeoffer/new/?partner=334235075&token=AdtgVEf8" target=_blank>Submit Items</a>';
						}
						?>
		</div> 
		<br>
	</div>
	<div class="hhdgfbd"></div>
	<div class="kjmhgd"></div>
	<section class="timer clearfix hidden"> </section>
	<section class="stop-game hidden"><h5>the game ended! choose
winner ...</h5></section>
		<section class="rounditems" style="margin: auto;">  
			<?php include "items.php";?>
		</section> 
	<section class="start-game"> 
		<a href="" target="_blank" class="stop"><img src="css/img/icon-play.png" height="24" width="20" alt=""></a>
		<h5>the game has begun! make a deposit!</h5>
	</section> 
	</div>

	

		<footer class="footer">
			<p>CSGO-Crazy.com © 2016</p>
			<p>Easy skins, easy life.</p>
			<img src="css/img/item-designed.png" height="57" width="82" alt="">
		</footer>
		
</div>
</body>
</html>


The EN/RU links shouldn't set any header or session info, but I'm not 100% certain. It doesn't appear to set any.

And @lithium720 I'm setting up error reporting now.

**Comment by jonnytothedee** [comment]
[index.txt](https://github.com/SmItH197/SteamAuthentication/files/190145/index.txt)
Woops my index file got cut off.

**Comment by RedSparr0w** [comment]
try putting
`require('steamauth/steamauth.php');`
at the top of your file

**Comment by jonnytothedee** [comment]
@RedSparr0w 
At the top of my settings.php?
Or my index.php?

**Comment by jonnytothedee** [comment]
@RedSparr0w 
Okay something very strange..
When I put:
require('steamauth/steamauth.php');
At the top of my settings.php, the whole site stops working...
When I go to csgo-crazy.com it's just a white screen

**Comment by SmItH197** [comment]
Is it inside the <?php tag?

**Comment by RedSparr0w** [comment]
not in your settings file, in your index.php file

**Comment by jonnytothedee** [comment]
Oh that's actually already in my index.php

<?php
@include_once "langdoc.php";
if(!isset($_COOKIE['lang'])) {
	setcookie("lang","ru",2147485547);
	$lang = "ru";
} else $lang = $_COOKIE["lang"];
$sitename = "CSGO-Crazy.com";
$title = "$sitename";
@include_once('set.php');
require('steamauth/steamauth.php');
	if(isset($_SESSION["steamid"])) {
include_once('steamauth/userInfo.php');}

**Comment by SmItH197** [comment]
Yes but it has to be the first thing after the<?php tag

**Comment by jonnytothedee** [comment]
It seems to be the same problem. It signs me in fine now, but it doesn't appear to be receiving any actual data.
It doesn't take my picture, it doesn't seem to get my username, and it isn't ACTUALLY recording any data into my database.

My index file starts out as this after changing it: 
<?php
require('steamauth/steamauth.php');
	if(isset($_SESSION["steamid"])) {
include_once('steamauth/userInfo.php');}
@include_once "langdoc.php";
if(!isset($_COOKIE['lang'])) {
	setcookie("lang","ru",2147485547);
	$lang = "ru";
} else $lang = $_COOKIE["lang"];
$sitename = "CSGO-Crazy.com";
$title = "$sitename";
@include_once('set.php');

**Comment by SmItH197** [comment]
See @blackcetha comment about SQL error

**Comment by jonnytothedee** [comment]
I'm not sure how I would go about correcting that error. 
I don't really see anything in phpmyadmin that could fix it.

**Comment by SmItH197** [comment]
Your using an incorrect login, check your username and password.

**Comment by jonnytothedee** [comment]
is there a way I can privately show you my set folder with my database information? I don't think I'm using an incorrect login. :/

**Comment by jonnytothedee** [comment]
well my set.php file

**Comment by jonnytothedee** [comment]
Actually, could you give it a try now?

**Comment by RedSparr0w** [comment]
yup redirecting perfectly for me now

**Comment by SmItH197** [comment]
Logging in works fine, can't see any SQL errors.

**Comment by jonnytothedee** [comment]
Sweet!
Thank you guys SO SO SO SO SO much!
Holy crap you're all some of the nicest people in the world.
Now it's just the nightmare of setting up my trade bot. OMG this is so exciting!!!!

**Comment by SmItH197** [comment]
No worries, closed.
