### ISSUE TITLE
Security error

### ISSUE THREAD

**Issue by RedSparr0w** [SmItH197/SteamAuthentication#125]
Hey,
I am getting a [Security error](http://i.imgur.com/q76bIrM.png) with the new demo site (using chrome).
have tried on 2 computers, get same problem.

![Deceptive site ahead - Attackers on bensmith.in may trick you into doing something dangerous like installing software or revealing your personal information (for example, passwords, phone numbers, or credit cards). - Automatically report details of possible security incidents to Google. Privacy policy
Back to safetyHide details Google Safe Browsing recently detected phishing on bensmith.in. - Phishing sites pretend to be other websites to trick you. - You can report a detection problem or, if you understand the risks to your security, visit this unsafe site.](http://i.imgur.com/q76bIrM.png) 

edit: i do not get a security warning on http://bensmith.in/example.php page only http://bensmith.in/demo.php
edit 2: i do not get a security warning when i login in an incognito session either

**Comment by lithium720** [comment]
Demo works fine for me in GC.

Example:
![Image](https://lithi.io/i/hw.png)

Demo:
![Image](https://lithi.io/i/Og.png)

**Comment by RedSparr0w** [comment]
only showed up for me after i signed in

**Comment by lithium720** [comment]
Still worked, both led to this page:
![Image](https://lithi.io/i/3r.png)

**Comment by RedSparr0w** [comment]
strange, not showing up for me now either, guess its closed XD

**Comment by SmItH197** [comment]
You had me very worried for a second. I wonder what caused it?

**Comment by RedSparr0w** [comment]
yeah quite strange, just one of those things i guess.

**Comment by bman46** [comment]
Check out this article: https://chrome.googleblog.com/2009/10/are-you-seeing-red.html?m=1
