### ISSUE TITLE
ADD currency 

### ISSUE THREAD

**Issue by HeeysamH** [SmItH197/SteamAuthentication#126]
Can i ADD A custom currency Like gems to each user. Its to my roulette website

**Comment by SmItH197** [comment]
Uhhhh what? What does this have to do with SteamAuthentication?

**Comment by HeeysamH** [comment]
Idk. But Like Do u know away to ADD it? I just thought it is related to steam auth.

**Comment by SmItH197** [comment]
Probably setup a database and store how much currency a user has in a table.

http://php.net/manual/en/book.mysqli.php

As this is a general php query and not a problem/question specifically regarding this project I'm going to close it. There are other forums where you can ask general php questions, not here.

**Comment by bman46** [comment]
You would probably get thire 64 steam Id and then you would store that In a DB and then when they purchase/earn/whatever you would try to find thire steam Id and check to see if it has any gems in it or you would add the steam id to the DB and then every time they want it you would pull it from the DB and check the amount. For help hitch MySQL check out issue #86
