### ISSUE TITLE
Good hostes?

### ISSUE THREAD

**Issue by HeeysamH** [SmItH197/SteamAuthentication#128]
Hey Mate

I know this is not a issue but.
Do you know any good hosts that works with this?
in the start i used 000webhost but it dosent work with this.
do you have any hosts free mayby?
Not localhost. That works life bullshit for me

**Comment by wortel538** [comment]
I use Hostinger.

**Comment by BlackCetha** [comment]
Unrelated, close please.

On a side note, most free hosting providers will not work.

**Comment by Boeng06** [comment]
Hmjhmmhmh
Den 29. mar. 2016 11.59 skrev "HeeysamH" <notifications@github.com>:

**Comment by bman46** [comment]
look in issue #129 they are all in there
