### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by HeeysamH** [SmItH197/SteamAuthentication#129]
Hey im trying it on my new website but it gives me a 404 not found error
pls help

Website: http://csgolifetime.esy.es/

**Comment by wortel538** [comment]
That means you didnt config it well, didnt register, or you have to wait.

Greetingz

**Comment by HeeysamH** [comment]
<?php
//Version 3.1.1
$steamauth['apikey'] = "KEY"; // Your Steam WebAPI-Key found at http://steamcommunity.com/dev/apikey
$steamauth['domainname'] = "http://www.csgolifetime.esy.es/"; // The main URL of your website displayed in the login page
$steamauth['logoutpage'] = ""; // Page to redirect to after a successfull logout (from the directory the SteamAuth-folder is located in) - NO slash at the beginning!
$steamauth['loginpage'] = ""; // Page to redirect to after a successfull login (from the directory the SteamAuth-folder is located in) - NO slash at the beginning!

// System stuff
if (empty($steamauth['apikey'])) {die("<div style='display: block; width: 100%; background-color: red; text-align: center;'>SteamAuth:<br>Please supply an API-Key!</div>");}
if (empty($steamauth['domainname'])) {$steamauth['domainname'] = $_SERVER['SERVER_NAME'];}
if (empty($steamauth['logoutpage'])) {$steamauth['logoutpage'] = $_SERVER['PHP_SELF'];}
if (empty($steamauth['loginpage'])) {$steamauth['loginpage'] = $_SERVER['PHP_SELF'];}
?>
I removed my key

**Comment by BlackCetha** [comment]
Not related, close

**Comment by bman46** [comment]
Its working now
maybe ur host had to set things up do some updates

**Comment by bman46** [comment]
And also, when getting a new website usually the host usually takes like a day to set it up and to confirm things

**Comment by bman46** [comment]
I figured out that @SmItH197 uses lite speed hosting by going to his website and typing in a bunch of random letters after the / mark (URL: http://www.litespeedtech.com/solutions ) and how i found it: http://bensmith.in/sdfsdfdsfsdfds

**Comment by SmItH197** [comment]
@bman46 if you read the 404 you would have seen:

Please be advised that LiteSpeed Technologies Inc. is not a web hosting
company and, as such, has no control over content found on this site.

So no, they are not my host.

**Comment by RedSparr0w** [comment]
A simple "who is" search could generally tell you. [=

http://www.enom.com seems to be the host

Sent from my iPhone

On 30/03/2016, at 11:06 am, bman46 <notifications@github.com<mailto:notifications@github.com>> wrote:


I figured out that @SmItH197<https://github.com/SmItH197> uses lite speed hosting by going to his website and typing in a bunch of random letters after the / mark (URL: http://www.litespeedtech.com/solutions ) and how i found it: http://bensmith.in/sdfsdfdsfsdfds

-

**Comment by bman46** [comment]
oh, lol

**Comment by SmItH197** [comment]
I use HostPresto.com

**Comment by bman46** [comment]
Scrap.tf uses ( https://www.linode.com/?r=de9bd66bad9c54ba45a176c116aff8cdc3a282ec ) linode, but it may be hard to set up since it is actually a command line thing but there is a article on how to set it up.
(they said it on there about [page)](https://scrap.tf/about)

**Comment by RedSparr0w** [comment]
The best "free" hosting I have found is http://c9.io
Note that it is meant for development so your server will be put in idle/sleep mode after 24hours ish of inactivity.
But it is very handy for testing everything out and making sure it all works whilst being able to edit from anywhere.

Sent from my iPhone

On 30/03/2016, at 11:50 am, bman46 <notifications@github.com<mailto:notifications@github.com>> wrote:


Scrap.tf uses ( https://www.linode.com/?r=de9bd66bad9c54ba45a176c116aff8cdc3a282ec ) linode, but it may be hard to set up since it is actually a command line thing but there is a article on how to set it up.
(they said it on there about page)<https://scrap.tf/about>

-

**Comment by Gummibeer** [comment]
It's going to be very offtopic - close please.
