### ISSUE TITLE
Sign in works perfectly, but database only gets steamid.

### ISSUE THREAD

**Issue by jonnytothedee** [SmItH197/SteamAuthentication#132]
My sign in works perfectly, as soon as the user signs in they're redirected to my index page, and their steamid goes straight into my database, but it doesn't record any other information. I have to manually insert their name and avatar every time. 
![screenie](https://cloud.githubusercontent.com/assets/16887976/14230921/17ef7e7c-f922-11e5-8337-5364f4648ff2.png)

I will provide any more information that you may need, but I'm just curious as to why this issue might be happening.

ANY input into why this might be happening is appreciated.
I sincerely hope this question hasn't already been answered, because I have been trying to figure this out all week. I promise I have looked as much as I possibly can into this issue and I haven't had any luck. 
If it has been answered I'm incredibly sorry for wasting your time.

**Comment by fnyah** [comment]
Do you mind asking how you even got the steamid into the database in the first place?

**Comment by jonnytothedee** [comment]
@fnyah oh wow I'm a derp that'd probably be useful information.
It's via openid on my website. 
www.csgo-crazy.com

**Comment by fnyah** [comment]
I'm not even able to get the steamid into my database :\

**Comment by RedSparr0w** [comment]
could you post your insert statement here

**Comment by jonnytothedee** [comment]
@RedSparr0w I'm incredibly sorry, but do you know where my insert statement should even be, I'm not  sure where I would have placed that. :c

**Comment by SmItH197** [comment]
What is your SQL statement?

**Comment by jonnytothedee** [comment]
Here is my topmenu.php, where the avatar should be displayed.
http://pastebin.com/wHdxDFTr

Here is the usersettings.php,
http://pastebin.com/gKRttk3g

and here's my userinfo.php
http://pastebin.com/LDLF4PdA

My auto update file for steam information has this as the statement:
if(isset($_SESSION["steamid"]))
{
	$time = time();
    mysql_query("UPDATE users SET lastseen=".$time." WHERE steamid=".$_SESSION['steamid']."");
	$banned=fetchinfo("ban","users","steamid",$_SESSION["steamid"]);
	$cbanned=fetchinfo("cban","users","steamid",$_SESSION["steamid"]);
	$mytrade = fetchinfo("tlink","users","steamid",$_SESSION["steamid"]);
	$admin = fetchinfo("admin","users","steamid",$_SESSION["steamid"]);
	$name=$steamprofile['personaname'];
	$name = mysql_real_escape_string($name);
	if($name)
	{
		mysql_query("UPDATE `users` SET `name`='".$name."', `avatar`='".$steamprofile['avatarfull']."' WHERE `steamid`='".$_SESSION["steamid"]."'");
	}

**Comment by jonnytothedee** [comment]
@fnyah what's your steam name? I can add you and try and talk you through it, I really struggled with it as well.

**Comment by fnyah** [comment]
@jonnytothedee
https://steamcommunity.com/id/blusod/

that would be awesome!

**Comment by SmItH197** [comment]
Try Moving your `include ('steamauth/userInfo.php');` to line 16 before `$time=time();`. I also suggest moving your `<!DOCTYPE html>` to line 109 before your <html> tag and moving your require steamauth.php to line 2 after your <?php tag.

**Comment by jonnytothedee** [comment]
@SmItH197 In which file?

**Comment by SmItH197** [comment]
usersettings.php

**Comment by SmItH197** [comment]
You shouldn't be using mysql. Read this about using mysqli: http://php.net/manual/en/mysqli.quickstart.statements.php

**Comment by jonnytothedee** [comment]
@SmItH197 
Those changes didn't seem to do anything :/ It still doesn't seem to be updating my database with any additional information. 
Does mysqli work via phpmyadmin?

**Comment by SmItH197** [comment]
Yes. Here is a basic sqli example, this is by no means perfect/safe/secure etc. and shouldn't be used as is, but just gives you an idea.

```php
<?php

$conn = mysqli_connect($servername, $username, $password, $dbname);

// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
} 

$addUser = "INSERT INTO users (ID,Name) VALUES ('" . $steamprofile['steamid'] . "', '" . $steamprofile['personaname'] . "')";

if (mysqli_query($conn,$addUser)) {
    
    echo "User added to DB";
            
} else {
    
    echo "Error adding user to database"
        
}
```

I don't want to sound rude, but I think you should read the php websites look at a few tutorials as its important to understand how the code your'e using works and from what I'm reading you don't fully grasp how to use SQL. This isn't really the place as its not the steamauth library causing the issue but you not preparing/using SQL queries properly, so I will close this now.
