### ISSUE TITLE
Undefined offset: 0 - userInfo.php

### ISSUE THREAD

**Issue by boxzmodder** [SmItH197/SteamAuthentication#134]
![udklip](https://cloud.githubusercontent.com/assets/5053450/15013206/57a525c2-11fe-11e6-9fda-ad110157fd5d.JPG)

I get this error when users log in to my website. ^^^

I check for if $_SESSION['steamid'] is set, and it indeed is.
What's wrong then?

**Comment by SmItH197** [comment]
What host do you use?

**Comment by boxzmodder** [comment]
I use Xampp with apache. It's a local server. :)

**Comment by boxzmodder** [comment]
I see that $_SESSION['steamid'] is set, but is empty (""). The session is also started because I used include("steamauth/steamauth.php");

**Comment by boxzmodder** [comment]
Okay, i solved it now. 

I put the $matches array from steamauth.php and put into $_SESSION. Then after the include statement, i the reassiged $_SESSION['steamid'] with $matches[1];

Now I can load everything :)
