### ISSUE TITLE
No OpenID Server found, clone but haven't found solution in any of other questions

### ISSUE THREAD

**Issue by FireWeb365** [SmItH197/SteamAuthentication#136]
No OpenID Server found at https://steamcommunity.com/openid, clone but haven't found solution in any of other questions...

I have paid hosting and tried changing between HTTP and HTTPS but no luck at all... as I am mainly C# programmer I don't know how to solve...

EDIT1: I have only access to ftp so no pinging and other solutions with console needed

EDIT2: Tried to run these php scripts on my Windows 2012 R2 Server VPS on WAMP it worked so yeah, problem is in webhost but it is solved as I will host it on my VPS...

**Comment by FireWeb365** [comment]
BTW I have only access to ftp so no pinging and other solutions with console needed

**Comment by BlackCetha** [comment]
Just comment in the open issue instead of opening a new one.
Just close it already if its working for you.
