### ISSUE TITLE
login issues

### ISSUE THREAD

**Issue by Vextraaa** [SmItH197/SteamAuthentication#138]
Hey guys I recently tried using the Steamauth login on my site which you can find at http://csgothunder.com/index.php I'm not quite sure as to what's causing this I've checked my api key and everything etc. If anyone has ever had this error and fixed it be sure to help me!

**Comment by BlackCetha** [comment]
There is not even a login button on your webpage.

What have you tried? At least pretent you put effort into it.

**Comment by Vextraaa** [comment]
http://csgothunder.com/index.php <<<

**Comment by BlackCetha** [comment]
Gives me 404
