### ISSUE TITLE
Invalid return URL 

### ISSUE THREAD

**Issue by Infrox** [SmItH197/SteamAuthentication#139]
Hey, I've been using the SteamAuth for a while now, everything was working fine, but today it stopped working for some reason, whenever I try to log-in through steam, I get:

```
Sorry!

An error was encountered while processing your request:

Invalid return URL


Here's a link to the Steam Community home page.
```

What's wrong?

**Comment by Segeco** [comment]
Can you post your SteamConfig.php Please? (Located in steamauth/SteamConfig.php).
Thanks.

**Comment by Infrox** [comment]
It's fixed already, apparently steam was down or something.
