### ISSUE TITLE
Steam OpenID Issues.

### ISSUE THREAD

**Issue by Vextraaa** [SmItH197/SteamAuthentication#140]
Hey guys I've been getting this problem on my website. After clicking the login button it changes the URL from http://csgothunder.com/ to http://csgothunder.com/?login But it doesn't redirect my website to the steam login page. I'm not too sure on what it could be. Feel free to check for yourself http://csgothunder.com/

**Comment by RedSparr0w** [comment]
i just get a coming soon page, not sure why you closed your other issue and opened a new one though? 

Also you http://csgothunder.com/index.php login button seems to redirect me fine.
