### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Logic-alFallacy** [SmItH197/SteamAuthentication#142]
I followed all the steps and it just says error.

**Comment by BlackCetha** [comment]
Information

**Comment by BlackCetha** [comment]
Seriously tho, how do you expect to help you with this little input?

Post links, screenshots, details about what you did etc.

**Comment by Logic-alFallacy** [comment]
I wasn't actually expecting anyone to respond so I was just checking if they would first.

**Comment by Logic-alFallacy** [comment]
![image](https://cloud.githubusercontent.com/assets/18654533/16177069/5e00ad66-361a-11e6-9d09-7d1ef9c76375.png)

**Comment by Logic-alFallacy** [comment]
I have taken the demo file and used that to get the login button, filled in all the steamauth details as appropriate. This is the page: http://139.59.173.110/

**Comment by BlackCetha** [comment]
I dont think it works with IP adresses. You will either have to test it locally or get a domain.

**Comment by RedSparr0w** [comment]
Don't think it does work with an ip as the domain , this is the address steam is trying to return to "http%3A%2F%2F%2F%3Flogin"

Which I think is equal to "http:///?login"

Sent from my iPhone

On 20/06/2016, at 12:00 am, BlackCetha <notifications@github.com<mailto:notifications@github.com>> wrote:


I dont think it works with IP adresses. You will either have to test it locally or get a domain.

-
