### ISSUE TITLE
User is not logged in.

### ISSUE THREAD

**Issue by Typ260** [SmItH197/SteamAuthentication#143]
Hey,

I got an error today that survived a Cache clear, Computer restart, Browser switch (FireFox, Opera, Chrome). I installed a fresh steamauth on a fresh Debian 8 Server (try out at dotaunion.com/demo.php | example.php). It forwards me to login, after successful steam login i get redirected to my page again. I get the "User is not logged in" then. Tried everything that came in my mind, as well as other solutions from previous Issues to this Git.

I put the valid API in the right place as well as Domain Name. Funny thing here to know is, the EXCACT same Site worked yesterday on another Server which was also running Debian 8/Apache/PHP5.

Any Ideas?

Greetz
David

**Comment by Typ260** [comment]
Soooo, it works now. Why? I have no idea. I installed a MySQL Server and php5-curl and php5-mysql. I dont know if this has anything to do with steam auth. If so, someone should add it to the Readme.md :D

**Comment by RedSparr0w** [comment]
99% sure you need curl to use use this, which would have been your problem [=

**Comment by Typ260** [comment]
Maybe it should be mentioned somewhere. Debian 8 Minimal didnt had curl from fresh installation. For all googlers : If you get the "User is not logged in."-Error, make sure you installed the php5-curl libary for your Apache2 Server. If you are not sure, put a Script on your Webserver that reads <?php phpinfo(); ?> and access it with your Browser and search (CTRL+F) for cURL. If it shows up, its installed and this Issue Thread has nothing to do with your problem.
