### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by S3cur1ty** [SmItH197/SteamAuthentication#144]
![1](https://cloud.githubusercontent.com/assets/1049081/16437278/55f1d082-3de0-11e6-9a67-0e5b279b2606.jpg)
![2](https://cloud.githubusercontent.com/assets/1049081/16437279/55f4ae88-3de0-11e6-893e-e51211b6739e.jpg)
![3](https://cloud.githubusercontent.com/assets/1049081/16437280/561465d4-3de0-11e6-88a7-01002b69179f.jpg)
![4](https://cloud.githubusercontent.com/assets/1049081/16437281/561739d0-3de0-11e6-88bb-21e4a0214bc2.jpg)

url: https://mysite.ru/index.php?janrain_nonce=2016-06-29T00%3A59%3A20ZBb12Qx&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=error&openid.error=realm+and+return_to+do+not+match

Please tell me what is wrong?

**Comment by RedSparr0w** [comment]
openid.error=realm+and+return_to+do+not+match

**Comment by S3cur1ty** [comment]
And what to do?

**Comment by SuperHB** [comment]
I'm having the same problem. I'm currently using this on a local server with XAMPP and when I press the login button, and sign in through steam, it doesn't log me in. It still shows the login button rather than the logout button. I tried this with both the example.php and demo.php available here and they both did the same

**Comment by RedSparr0w** [comment]
what is the url when you click the login button?

`https://steamcommunity.com/openid/login?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=checkid_setup&openid.return_to=http%3A%2F%2Fcsgo.redsparr0w.com%2Fhome%3Flogin&openid.realm=http%3A%2F%2Fcsgo.redsparr0w.com&openid.ns.sreg=http%3A%2F%2Fopenid.net%2Fextensions%2Fsreg%2F1.1&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select`

**Comment by SuperHB** [comment]
> https://steamcommunity.com/openid/login?openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=checkid_setup&openid.return_to=http%3A%2F%2Flocalhost%2F%3Flogin&openid.realm=http%3A%2F%2Flocalhost&openid.ns.sreg=http%3A%2F%2Fopenid.net%2Fextensions%2Fsreg%2F1.1&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select

**Comment by RedSparr0w** [comment]
are you getting the same error as above

https://mysite.ru/index.php?janrain_nonce=2016-06-29T00%3A59%3A20ZBb12Qx&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=error& **openid.error=realm+and+return_to+do+not+match** or a different error?

 because your realm and return to seem to match in the steam url

**Comment by SuperHB** [comment]
I don't get any error.

**Comment by RedSparr0w** [comment]
what url is shown once you are redirected back to your site from steam?

**Comment by SuperHB** [comment]
None. It would just be "localhost"

**Comment by RedSparr0w** [comment]
Are cookies enabled?

If you refresh the page after logging in does it work?

**Comment by SuperHB** [comment]
Refreshing the page after login doesn't change anything

**Comment by Zortex04** [comment]
Hello so im having not relly an issue but its sure anoying when i press sign in on the steam site from the button on my page it just stays there the only way of me actually getting back on the page logged in is pressing back which i dont wanna do myself i want it to do that automaticly
