### ISSUE TITLE
What about steamID?

### ISSUE THREAD

**Issue by darkthefirst** [SmItH197/SteamAuthentication#145]
Not SteamID64. Type STEAM_0: 1: 91221650

**Comment by BlackCetha** [comment]
Where exactly is your technical problem?

**Comment by darkthefirst** [comment]
How can I get Steam ID?

>

**Comment by RedSparr0w** [comment]
`$steamprofile['steamid']` try reading the [readme](https://github.com/SmItH197/SteamAuthentication#using-profile-variables) before asking questions.

**Comment by RedSparr0w** [comment]
try something like this api:
`https://steamid.eu/api/convert.php?input=STEAMID64`

**Comment by darkthefirst** [comment]
Thank You!

**Comment by BlackCetha** [comment]
Or something like this: https://github.com/DoctorMcKay/php-steamid
