### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by TristanP13** [SmItH197/SteamAuthentication#146]
Could you please release this under an MIT license or similar? I would like to be able to use this for a project.

**Comment by bman46** [comment]
what kind of project are u going to use this for?

**Comment by TristanP13** [comment]
@bman46 For a web administration panel that I'm planning on reselling. This is the best one available but without a license I technically can't do it.

**Comment by bman46** [comment]
K, in that case it is up to @SmItH197 to add a license, but in the mean time you may want to check out the licenses from lightopenid and JTX (I don't know of that will affect anything, but it always good to check) you can find the links in the foreword section in the read me.

**Comment by SmItH197** [comment]
Added, good luck!
