### ISSUE TITLE
Parse error: syntax error, unexpected end of file in /home/u136844693/public_html/steamauth/userInfo.php on line 51

### ISSUE THREAD

**Issue by kaMMi21** [SmItH197/SteamAuthentication#147]
After logging in to the site by the steam , I received this error ... How to fix it or if there is someone who will give advice do this to me ? :(

**Comment by SmItH197** [comment]
Assuming you haven't changed userinfo.php then it's probably a syntax error in your file. Could you post your code that you're implementing the library in?

**Comment by kaMMi21** [comment]
You mean the code of userinfo.php ?

**Comment by kaMMi21** [comment]
`<?php
        include("settings.php");
    if (empty($_SESSION['steam_uptodate']) or $_SESSION['steam_uptodate'] == false or empty($_SESSION['steam_personaname'])) {
        $url = file_get_contents("http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=".$steamauth['24F76762D35C95092396DB68F2CADB80']."&steamids=".$_SESSION['steamid']);
        $content = json_decode($url, true);
        $_SESSION['steam_steamid'] = $content['response']['players'][0]['steamid'];
        $_SESSION['steam_communityvisibilitystate'] = $content['response']['players'][0]['communityvisibilitystate'];
        $_SESSION['steam_profilestate'] = $content['response']['players'][0]['profilestate'];
        $_SESSION['steam_personaname'] = mysql_real_escape_string($content['response']['players'][0]['personaname']);
        $_SESSION['steam_lastlogoff'] = $content['response']['players'][0]['lastlogoff'];
        $_SESSION['steam_profileurl'] = $content['response']['players'][0]['profileurl'];
        $_SESSION['steam_avatar'] = $content['response']['players'][0]['avatar'];
        $_SESSION['steam_avatarmedium'] = $content['response']['players'][0]['avatarmedium'];
        $_SESSION['steam_avatarfull'] = $content['response']['players'][0]['avatarfull'];
        $_SESSION['steam_personastate'] = $content['response']['players'][0]['personastate'];
        if (isset($content['response']['players'][0]['realname'])) {
                   $_SESSION['steam_realname'] = mysql_real_escape_string($content['response']['players'][0]['realname']);
               } else {
                   $_SESSION['steam_realname'] = "Real name not given";
        }
        $_SESSION['steam_primaryclanid'] = $content['response']['players'][0]['primaryclanid'];
        $_SESSION['steam_timecreated'] = $content['response']['players'][0]['timecreated'];
        $_SESSION['steam_uptodate'] = true;
    }
   
    $steamprofile['steamid'] = $_SESSION['steam_steamid'];
    $steamprofile['communityvisibilitystate'] = $_SESSION['steam_communityvisibilitystate'];
    $steamprofile['profilestate'] = $_SESSION['steam_profilestate'];
    $steamprofile['personaname'] = $_SESSION['steam_personaname'];
    $steamprofile['lastlogoff'] = $_SESSION['steam_lastlogoff'];
    $steamprofile['profileurl'] = $_SESSION['steam_profileurl'];
    $steamprofile['avatar'] = $_SESSION['steam_avatar'];
    $steamprofile['avatarmedium'] = $_SESSION['steam_avatarmedium'];
    $steamprofile['avatarfull'] = $_SESSION['steam_avatarfull'];
    $steamprofile['personastate'] = $_SESSION['steam_personastate'];
    $steamprofile['realname'] = $_SESSION['steam_realname'];
    $steamprofile['primaryclanid'] = $_SESSION['steam_primaryclanid'];
    $steamprofile['timecreated'] = $_SESSION['steam_timecreated'];
?>
 <?php
        include("settings.php");
     if (empty($_SESSION['steam_uptodate']) or $_SESSION['steam_uptodate'] == false or empty($_SESSION['steam_personaname'])) {
-        $url = file_get_contents("http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=".$steamauth['apikey']."&steamids=".$_SESSION['steamid']);
+        $url = url_get_contents("http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=".$steamauth['apikey']."&steamids=".$_SESSION['steamid']);
         $content = json_decode($url, true);
         $_SESSION['steam_steamid'] = $content['response']['players'][0]['steamid'];
         $_SESSION['steam_communityvisibilitystate'] = $content['response']['players'][0]['communityvisibilitystate'];
     $steamprofile['timecreated'] = $_SESSION['steam_timecreated'];
 
function url_get_contents ($Url) { if (!function_exists('curl_init')){ die('CURL is not installed!'); } $ch = curl_init(); curl_setopt($ch, CURLOPT_URL, $Url); curl_setopt($ch, CURLOPT_RETURNTRANSFER, true); $output = curl_exec($ch); curl_close($ch); return $output; }
 ?>`

**Comment by SmItH197** [comment]
I meant the code of the file you've created. Have you altered userinfo.php at all?

**Comment by kaMMi21** [comment]
Yes I copied from one of the topics I changed my API KEY.

**Comment by SmItH197** [comment]
Why have you pasted the below into the file?
```php
<?php
        include("settings.php");
     if (empty($_SESSION['steam_uptodate']) or $_SESSION['steam_uptodate'] == false or empty($_SESSION['steam_personaname'])) {
-        $url = file_get_contents("http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=".$steamauth['apikey']."&steamids=".$_SESSION['steamid']);
+        $url = url_get_contents("http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=".$steamauth['apikey']."&steamids=".$_SESSION['steamid']);
         $content = json_decode($url, true);
         $_SESSION['steam_steamid'] = $content['response']['players'][0]['steamid'];
         $_SESSION['steam_communityvisibilitystate'] = $content['response']['players'][0]['communityvisibilitystate'];
     $steamprofile['timecreated'] = $_SESSION['steam_timecreated'];

function url_get_contents ($Url) { if (!function_exists('curl_init')){ die('CURL is not installed!'); } $ch = curl_init(); curl_setopt($ch, CURLOPT_URL, $Url); curl_setopt($ch, CURLOPT_RETURNTRANSFER, true); $output = curl_exec($ch); curl_close($ch); return $output; }
 ?>`

**Comment by kaMMi21** [comment]
Hmmm I do not know why. I have a question to the Lord. If I give you data to FTP is given to you can do it will be faster .

**Comment by SmItH197** [comment]
If you don't know why it's there just delete it

**Comment by kaMMi21** [comment]
But it was " corrected " version

**Comment by kaMMi21** [comment]
Now this error 
Parse error: syntax error, unexpected end of file in /home/u136844693/public_html/steamauth/userInfo.php on line 27

**Comment by SmItH197** [comment]
Post a link to your website?

**Comment by SmItH197** [comment]
Userinfo.php should be longer than 27 lines

**Comment by SmItH197** [comment]
Post your userinfo again?

**Comment by kaMMi21** [comment]
http://csgotop.pe.hu/ My website link

**Comment by kaMMi21** [comment]
Now i have this error when i replace 

Warning: require(SteamConfig.php): failed to open stream: No such file or directory in /home/u136844693/public_html/steamauth/userInfo.php on line 3

Fatal error: require(): Failed opening required 'SteamConfig.php' (include_path='.:/opt/php-5.5/pear') in /home/u136844693/public_html/steamauth/userInfo.php on line 3

**Comment by kaMMi21** [comment]
Man ?

**Comment by SmItH197** [comment]
Can I ask what your site does? Also you've got a load of SQL errors, I would switch from SQL to sqli

**Comment by kaMMi21** [comment]
Can I have more clearly ? I'm not good at English

**Comment by SmItH197** [comment]
Sorry!

What do users do on your website?

**Comment by kaMMi21** [comment]
Nothing happened :) I want to do jackpot

**Comment by SmItH197** [comment]
Be very careful, gambling sites violate Steams API agreement. Please read:

http://store.steampowered.com/news/22883/

**Comment by SmItH197** [comment]
> Using the OpenID API and making the same web calls as Steam users to run a gambling business is not allowed by our API nor our user agreements. We are going to start sending notices to these sites requesting they cease operations through Steam, and further pursue the matter as necessary. Users should probably consider this information as they manage their in-game item inventory and trade activity.

**Comment by kaMMi21** [comment]
I read that I am aware of that. Can you help me ?

**Comment by SmItH197** [comment]
Sorry, but as your site will be violating Steams API and user agreements I will not provide any support. It may seem harsh but it's the path I've decided to take.

Many thanks for your understanding,

SmItH197
