### ISSUE TITLE
New steam login buttons

### ISSUE THREAD

**Issue by BlackCetha** [SmItH197/SteamAuthentication#148]
I just noticed that steam updated their login button images after the gambling site shutdown.

http://steamcommunity-a.akamaihd.net/public/images/signinthroughsteam/sits_01.png
http://steamcommunity-a.akamaihd.net/public/images/signinthroughsteam/sits_02.png

Since they have updated links and I don't have the time to test if the old ones still work, I'd say we update as soon as possible.

**Comment by BlackCetha** [comment]
They are grey, contain a typo and are generally just ugly btw

**Comment by SmItH197** [comment]
wow, they certainly ain't pretty! Will get these added now.

**Comment by SmItH197** [comment]
Done!
