### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by giesche** [SmItH197/SteamAuthentication#151]
I need to retrive cookie from steamcommunity  for making steam trade by my application. User login to my app by openId (I use steamauth library). Login in is working but i need cookie from steamcommunity (sessionid and steamLoginSecure). I see this cookie in the firebug  on the cookies list but I can’t get it. 
So far I try two ways:
First i was trying to get cookie from the server site:  $_COOKIE[‘session’]. 
And also I was try to get cookie in the browser by „document.cookie”.
Both method don’t working.

**Comment by SmItH197** [comment]
I don't feel this relates to this project, as a result I'm closing this.
