### ISSUE TITLE
Login button not working with laravel php framework!

### ISSUE THREAD

**Issue by TheFlyingVoid** [SmItH197/SteamAuthentication#153]
Since the first website creation without a php framework, I am working on converting all of the website over to use the laravel framework. This raises the problem of nothing happening when clicking on the "Login" button. The buttons address is "http://localhost:8000/?login", and this just makes the page load a little bit and then stops loading and nothing happens. How do I fix this?

**Comment by ATomIK** [comment]
First you need to learn laravel.

**Comment by TheFlyingVoid** [comment]
Yes, have since done this. It was pretty obvious what what's wrong. Learned laravel and also learned to only use laravel packages within the laravel project. Thanks for the help.
