### ISSUE TITLE
Non secure (https) loginbutton

### ISSUE THREAD

**Issue by SwissBorn2Frag** [SmItH197/SteamAuthentication#154]
If you implement this library to a https site, then the loginbutton is marked as unsecure element because its requested with http. 

Any ideas how to fix?
Unfortunately the same url isn't available as https. The certificate there is unsecure.

**Comment by SwissBorn2Frag** [comment]
This can be used. (Found it here ->  https://steamcommunity.com/dev?l=german):

https://steamcommunity-a.akamaihd.net/public/images/signinthroughsteam/sits_01.png"

So in your steamauth.php something like that would be the solution:

if( !isset($_SERVER['HTTPS'] ) ) {
      Your already existing loginbutton code
} else {
      Your already existing loginbutton code with https Url to the pictures. 
}

**Comment by RedSparr0w** [comment]
or something like this would work and be easier:
```php
function loginbutton($buttonstyle = "square") {
	$button['rectangle'] = "01";
	$button['square'] = "02";
	$button = "<a href='?login'><img src='http".(isset($_SERVER['HTTPS']) ? "s" : "")."://steamcommunity-a.akamaihd.net/public/images/signinthroughsteam/sits_".$button[$buttonstyle].".png'></a>";
	
	echo $button;
}
```
