### ISSUE TITLE
OpenID Registration

### ISSUE THREAD

**Issue by ocaiquemello** [SmItH197/SteamAuthentication#155]
Hello! Im building an eSports CSGO team manager and i wish to implement OpenID so players, managers and coach can signin. I was wondering if OpenID is implemented, anyone with Steam can signin into my system, and it needs to be restrict to the people listed above. Can OpenID provide some registration or restriction so only registered people can signin? Thanks in advance and sorry for my English.

**Comment by bman46** [comment]
I would do that by adding a MySQL database and putting all of the steam ids (the number one, not the username) allowed into there and then when they sign in you would use a if statement to verify if they are signed up.

**Comment by ocaiquemello** [comment]
Thanks for the answer, so OpenID has a registration class that input this data or will i have to build it?

**Comment by bman46** [comment]
U will have to build it

**Comment by ocaiquemello** [comment]
Ok, thanks for the answer. It was helpful!
