### ISSUE TITLE
Help with something?

### ISSUE THREAD

**Issue by Vextraaa** [SmItH197/SteamAuthentication#156]
Hey guys so basically I want to make my login work like this

*click login* > redirects to other website for login > log in > *redirects back to main site*

If anyone understands what I'm trying to explain drop a comment and help out! Thanks!

**Comment by SmItH197** [comment]
1. Put a steam login button on your main site which links to other website.
2. On other website implement the login code.
3 set the `$steamauth['loginpage']` to a page which will redirect back to your main site using a header redirect or something.

**Comment by Vextraaa** [comment]
The two pages that I wish to link are on the same domain.
