### ISSUE TITLE
SteamAuth OpenID return address

### ISSUE THREAD

**Issue by lithium720** [SmItH197/SteamAuthentication#157]
When you click on a 'Sign in through Steam' link, it saves the return to address in the GET data on the steam site but returns you to the root address instead.

How can we actually use the 'return to'?

Example can be seen if you sign in to my website from the setup instructions page @ https://lithi.io/setup-instructions.php
You can see openid.return_to=http%3A%2F%2Flithi.io%2Fsetup-instructions.php in the address bar.

**Comment by lithium720** [comment]
I've also got a link on the index page. I was more looking for a way to make it dynamically just return you to the page you were on when you clicked "Sign in with Steam"

**Comment by SmItH197** [comment]
That will, $steamauth['loginpage'] is the page you want to be returned to when you've logged in.

**Comment by lithium720** [comment]
That makes it so when someone uses the sign in through Steam button on the index it takes them to setup, I want it to return them to the page they clicked the button on. The button is on multiple pages (setup and the index, for example).

Sorry for the confusion, I'm trying to make it dynamic, since I saw the return to address in the OpenID string.

**Comment by lithium720** [comment]
I ended up storing the page they were on when the clicked the login button in a $_SESSION variable and sent them back where they were after logging in.
