### ISSUE TITLE
SteamAuth returns a blank Steam ID and no User Data

### ISSUE THREAD

**Issue by Gergo4961** [SmItH197/SteamAuthentication#158]
Hello!

I'm trying to install a site I made on the FTP I got from the owner, and while the login and everything works perfectly on my end (on my local server), when I upload the files SteamAuth simply returns an empty Steam ID, and no other user data (Name, avatar in particular).

The API and the settings are correct, I even tried updating to this newer version and it still did not work.

Any help is appreciated!

~ Gergő

**Comment by Gergo4961** [comment]
Update:

This part returns bool(false) for some odd reason: @ $url = file_get_contents("http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=".$steamauth['apikey']."&steamids=".$_SESSION['steamid']);

**Comment by Gergo4961** [comment]
Okay, in case anyone has this problem it's most likely your host, just use CURL, here's a copy-paste solution to this error:

$apiurl="http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=".$steamauth['apikey']."&steamids=".$_SESSION['steamid']."";
$url=get_data($apiurl);

function get_data($url)
{
	$ch = curl_init();
	$timeout = 5;
	curl_setopt($ch, CURLOPT_URL, $url);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, $timeout);
	$data = curl_exec($ch);
	curl_close($ch);
	return $data;
}

**Comment by lithium720** [comment]
Steam may be having difficulties. Logins are no longer working on my site without having changed anything.

**Comment by RedSparr0w** [comment]
seems to have been working fine for me all day.

**Comment by lithium720** [comment]
It ended up being on my end, configuration error.
