### ISSUE TITLE
Cookie TIME

### ISSUE THREAD

**Issue by mworkg** [SmItH197/SteamAuthentication#163]
The cookie expire every 4-5 hours? How to make expire time 4-5 days?

**Comment by RedSparr0w** [comment]
Something like this should do
```php
ini_set(’session.gc_maxlifetime’, 7*24*30*60); // 7 Days
session_set_cookie_params(7*24*60*60); // 7 Days
session_start();
```

**Comment by mworkg** [comment]
Not work.

**Comment by RedSparr0w** [comment]
Try clearing your cookies.

**Comment by mworkg** [comment]
I tried to do this not working.

**Comment by SeanColombo** [comment]
This is a general Apache (or PHP, if you count ini_set()) issue, it should probably be closed.
