### ISSUE TITLE
Access Forbidden after logging in steam

### ISSUE THREAD

**Issue by Vicsuka** [SmItH197/SteamAuthentication#164]
Hi!

I'm not sure why this issue comes up after logging in. Should I somehow connect it with my database?
https://gyazo.com/db8289efa046db6ce272a2bc5d6b63ee

**Comment by BlackCetha** [comment]
There are constantly issues with free hosting providers.
I don't think there is any problem with the libary. Please close this issue.

You can and should develop locally using a server suite like XAMPP or WiNGINX.
Free hosting is always very limited and should not be used for anything besides maybe a family/event website.
