### ISSUE TITLE
User is not logged in

### ISSUE THREAD

**Issue by klaasa** [SmItH197/SteamAuthentication#165]
I am busy updating my site and saw this Steam Authentication script. Everthing works fine and all, but when I try to login I get the error: "User is not logged in". I saw some others had this same problem and tried some of their fixes, but no luck. cURL is installed on my server.

Website page with the problems: arkmap.org/dev/index.php?page=tribe

**Comment by BlackCetha** [comment]
I cannot reproduce your error. Everything seems to work.

**Comment by klaasa** [comment]
Hmm it doesn't display the error anymore, but it isn't setting de steamid session. So I still think it has the same error, but without displaying it.
