### ISSUE TITLE
I have a problem when I click the button

### ISSUE THREAD

**Issue by xXToXiiCDOGZz** [SmItH197/SteamAuthentication#171]
So, my problem is that when I click the button (the login button), the site adds just ?login at the end of the url and the first line in index.php is: No OpenID Server found at http://steamcommunity.com/openid

What can I do? Thanks anyway

**Comment by minecraftinventz** [comment]
Having same issue. Just adds  ?login

**Comment by nl-fell** [comment]
Same here

**Comment by BlackCetha** [comment]
Duplicate of #166.
