### ISSUE TITLE
500 Internal Server Error from 000Webhost?

### ISSUE THREAD

**Issue by Marow** [SmItH197/SteamAuthentication#172]
Hi,

i get so much errors with message:
`GET http://stuffs.000webhostapp.com/cs.php?cookie=lang=en;%20PHPSESSID=khlinm290q0t698copmik6cp12;%20_ga=GA1.2.375876183.1488986657 500 (Internal Server Error)`

But i dont know why. I dont have an 000webhost Server or anything.
When i "Inspect Site" and look to console, it spams so much that my console crashed...

All the time, the Same error...
Can anyone help me pls?

**Comment by BlackCetha** [comment]
This is completely unrelated to this libary. Please close this issue.

You could download and/or open all javascript code used on your website and search for the address it's trying to GET.

**Comment by Marow** [comment]
This is the Problem. I dont find anything on my Site with this address.
And when i delete Steamauth from my Project, i dont get this Errors.

So i mean it must come from steamauth
