### ISSUE TITLE
Safety Precautions (not really an issue)

### ISSUE THREAD

**Issue by timeisthelimit** [SmItH197/SteamAuthentication#183]
Hi,

I've just implemented the steam login to my website (not live yet). I'm just wondering if there are any safety/security precautions I need to take if the website is to go public? For example: is it possible for somebody to impersonate somebody else's steam account by omitting the redirect to steam's official login page. The reason I'm asking this is because, really, I'm just storing their steam id in the database so I can relate data to it. So with the code as it is right now, taken from here, possible for someone to bypass the steam authentication just knowing the person's steam id?

I'd appreciate it if you could point out any security precautions that I should take to prevent this if it could happen.

Thank you.

**Comment by bman46** [comment]
For this library I have not found any issues concerning security. However issues occur with security related to the server application and database.

**Comment by timeisthelimit** [comment]
Thank you

**Comment by RedSparr0w** [comment]
Just make sure to sanitise data such as their username, otherwise you will be vulnerable to SQL injections among other things.

Sent from my iPhone

On 6/08/2017, at 8:52 AM, Oskar Aleksander Jankowski <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you

**Comment by timeisthelimit** [comment]
Thanks
