### ISSUE TITLE
APIKEY not given when set

### ISSUE THREAD

**Issue by DubStepMad** [SmItH197/SteamAuthentication#190]
Current setup:
Windows server 2016
xampp running apache 32bit, can't remember what php version but I believe its the latest at the current date.

Directory layout:
https://gyazo.com/d896d6f6de97d7bb960ba4b84a0d722b

steamlogin.php code:
https://pastebin.com/sZtEas9v

SteamConfig.php (Removed API Key to not share it):
https://gyazo.com/f0c3921b33f4dcbd611293df65aa4543

Outcome:
https://gyazo.com/22e7e3a42d78ffeb2954271797624341

Not sure what I have did wrong her but I believe I have followed the installation correctly

**Comment by BlackCetha** [comment]
You need to put your configuration settings in the parenthesis after the equals sign.

**Comment by DubStepMad** [comment]
Well I feel like an idiot, got so much on my mind I over looked them, thank you.
