### ISSUE TITLE
offset 0 in..

### ISSUE THREAD

**Issue by AlaaAo** [SmItH197/SteamAuthentication#191]
I always get these errors when im not logged in into my website . if i logged in the errors are gone 

https://imgur.com/a/ReO3C

Any idea?

**Comment by BlackCetha** [comment]
This is a bug in the library. From just the screenshot it seems that for every request made while not logged in theres an API call made. In default installations of PHP the error message just gets discarded.
You can edit the first if-statement in `steamauth/userInfo.php` to also check `isset($_SESSION["steamid"])` as far as I can see.

**Comment by AlaaAo** [comment]
yep it works now thanks

**Comment by BlackCetha** [comment]
Can you make sure it's working properly? If it does, please send us a PR.
It'll take some time to get merged, but this certainly needs fixing ASAP.

**Comment by AlaaAo** [comment]
I can confirm now .. its working like a charm
