### ISSUE TITLE
500

### ISSUE THREAD

**Issue by UT-Tom** [SmItH197/SteamAuthentication#193]
quick question,

is anyone else unable to login? maybe it's just my account, but i'm getting redirected to https://steamcommunity.com/openid/login with a 500 error.. tried logging in through both the demo site and a few other sites using openid.

**Comment by IamOmni** [comment]
This has worked perfectly until now. 

I suspect there's something wrong on VALVE's side.

**Comment by UT-Tom** [comment]
so it's not just me? i haven't seen anyone complain about it on steam auth site's forums probably because they can't log in :v

**Comment by IamOmni** [comment]
Yeah,

Because people who are logged in won't notice any error.

People who are unabke to log in couldn't complain.

**Comment by UT-Tom** [comment]
we're good now. something was going on yesterday that non of those steam-status sites could pick up on.
