### ISSUE TITLE
Could not resolve host: steamcommunity.com

### ISSUE THREAD

**Issue by mySNAKE** [SmItH197/SteamAuthentication#194]
Hi.

Everything is on the screenshot, I always use this library but still on http sites, now that I am in https the error message is the following: "Could not resolve host: steamcommunity.com"

https://i.gyazo.com/511680b94f52836754b9b5a01ab4f335.png

Thank you in advance and sorry for my English.

**Comment by BlackCetha** [comment]
I think the error message is self-explaining: Your PHP installation can't resolve the address. This could be a wrong configuration in `/etc/resolv.conf` or in PHP.
Just google the error message and you'll probably find a solution.

**Comment by mySNAKE** [comment]
I already google the error, and i find this https://github.com/SmItH197/SteamAuthentication/issues/90 but all not working..

This is my resolv.conf
https://pastebin.com/R1hJ37dV

**Comment by mySNAKE** [comment]
The problem has been solved.

If you have this problem before, i modify my resolv.conf to : 

> domain openstacklocal
> search openstacklocal
> nameserver 51.255.49.241
> nameserver 51.255.49.241

and after i go to my SSH and i insert **service network restart**

Thank you @BlackCetha  for putting me on the right road to do my research :)
