### ISSUE TITLE
Problem: Undefined offset: 0 in userInfo.php

### ISSUE THREAD

**Issue by LonsterTheMonster** [SmItH197/SteamAuthentication#196]
I am new to php and i kinda understand it but i dont know why the code wont work that i have been working on

The Errors are below

`Notice: Undefined index: steamid in C:\xampp\htdocs\Marketwh.com\steamauth\userInfo.php on line 4

Notice: Undefined offset: 0 in C:\xampp\htdocs\Marketwh.com\steamauth\userInfo.php on line 6

Notice: Undefined offset: 0 in C:\xampp\htdocs\Marketwh.com\steamauth\userInfo.php on line 7

Notice: Undefined offset: 0 in C:\xampp\htdocs\Marketwh.com\steamauth\userInfo.php on line 8

Notice: Undefined offset: 0 in C:\xampp\htdocs\Marketwh.com\steamauth\userInfo.php on line 9

Notice: Undefined offset: 0 in C:\xampp\htdocs\Marketwh.com\steamauth\userInfo.php on line 10

Notice: Undefined offset: 0 in C:\xampp\htdocs\Marketwh.com\steamauth\userInfo.php on line 11

Notice: Undefined offset: 0 in C:\xampp\htdocs\Marketwh.com\steamauth\userInfo.php on line 12

Notice: Undefined offset: 0 in C:\xampp\htdocs\Marketwh.com\steamauth\userInfo.php on line 13

Notice: Undefined offset: 0 in C:\xampp\htdocs\Marketwh.com\steamauth\userInfo.php on line 14

Notice: Undefined offset: 0 in C:\xampp\htdocs\Marketwh.com\steamauth\userInfo.php on line 15

Notice: Undefined offset: 0 in C:\xampp\htdocs\Marketwh.com\steamauth\userInfo.php on line 21

Notice: Undefined offset: 0 in C:\xampp\htdocs\Marketwh.com\steamauth\userInfo.php on line 22

Notice: Undefined index: steamid in C:\xampp\htdocs\Marketwh.com\index.php on line 8`

The Code i have in the index.php is below

`<?php

	require 'steamauth/steamauth.php';  
	require 'steamauth/userInfo.php';
		
	if(!isset($_SESSION['steamid'])) 
	{
		$id = $_SESSION['steamid'];
	} 
	else 
	{
		#Bot Logged In
	}
?> `

any help is apprieciated thanks

**Comment by fedorovvldmr** [comment]
!isset($_SESSION['steamid']) ====> $_SESSION['steamid'] is null

**Comment by LonsterTheMonster** [comment]
@fedorovvldmr I am sorry but the `! isset($_SESSION['steamid']) ====> $_SESSION['steamid'] is null ` Where is that my code or in the userInfo.php?

**Comment by LonsterTheMonster** [comment]
@fedorovvlfmr Thank You i fixed it that helped thanks alot
