### ISSUE TITLE
Steam Login Result: Forbidden

### ISSUE THREAD

**Issue by LonsterTheMonster** [SmItH197/SteamAuthentication#197]
I sign into the code i pressed sign in as below
![login](https://user-images.githubusercontent.com/12468728/35469733-de5afc4c-0309-11e8-9165-19f0e815bb3d.PNG)

and when i do in the next picture it shows the forbidden output
![forbidden](https://user-images.githubusercontent.com/12468728/35469732-de495c12-0309-11e8-98a1-ae01ef29b968.PNG)

What is wrong?

**Comment by BlackCetha** [comment]
Your webserver can't read the directory you're trying to access because it lacks the filesystem permissions.

**Comment by LonsterTheMonster** [comment]
@BlackCetha how can i fix that i have it on my pc through xampp how do i enable the permissions?

**Comment by LonsterTheMonster** [comment]
@BlackCetha  I made sure the file(s) are not on readonly and they were but it still has the forbidden outcome

**Comment by LonsterTheMonster** [comment]
Figured it out i think it was where xampp kept redirecing becasue of some code in php and it basically called the steam api too many times and was put on a cooldown becasue it works now
