### ISSUE TITLE
Composer installation

### ISSUE THREAD

**Issue by maxorlovsky** [SmItH197/SteamAuthentication#198]
I have a question, is this proper package for composer https://packagist.org/packages/smith197/steamauthentication ?
As there are no information what-so-ever in README of the project. When I'm trying to install it with composer I receive error.

> [InvalidArgumentException]
> Could not find package smith197/steamauthentication.
> 
> Did you mean this?
> smith197/steamauthentication

**Comment by BlackCetha** [comment]
I'm not familiar with composer, but we have a file called "composer.json" that points to that URL.

**Comment by maxorlovsky** [comment]
Do you know who registered your library on packagist website?

**Comment by maxorlovsky** [comment]
Found it - https://github.com/SmItH197/SteamAuthentication/commits?author=MartinBecker
He tried to set it up, but he it incorrectly..

**Comment by BlackCetha** [comment]
Can you shoot us a PR so we can get this to work properly?

**Comment by maxorlovsky** [comment]
Sure - https://github.com/SmItH197/SteamAuthentication/pull/206
After it will be merged if package was properly configured on packagist.org it will automatically identify changes. If not @MartinBecker need to do it manually or give maintainer to someone [here](https://packagist.org/packages/smith197/steamauthentication) who can do it manually or configure for it to happen automatically on every git push request.
