### ISSUE TITLE
Not work at all

### ISSUE THREAD

**Issue by AngelTs** [SmItH197/SteamAuthentication#201]
After successful login, none user data has been obtained

**Comment by BlackCetha** [comment]
Please include your configuration in error reports. Make sure to strip your API key.

**Comment by AngelTs** [comment]
There is no any errors- $steamprofile['avatarfull']= EMPTY?!?!?!
Here is the result of example.php after successful log in on my site:
...
Welcome back </br>here is your avatar: </br><img src="" title="" alt="" /><br><script>loadDoc()
...

**Comment by bmoconno** [comment]
If you're on a real host, you should probably check your server logs to see what's happening.

I'm betting you've got allow_url_fopen turned off or something silly like that preventing you from actually getting the data back from the API call.

**Comment by AngelTs** [comment]
# @bmoconno Thank you so much for your help- now all works ok.
Can you check my other question [here](https://github.com/SmItH197/SteamAuthentication/issues/207)
