### ISSUE TITLE
How to speed up redirect in steam login?

### ISSUE THREAD

**Issue by LonsterTheMonster** [SmItH197/SteamAuthentication#202]
It takes forever for the openid to take effect and go back to the site i have it on what are some of the possibilities that is could be i have a  server on 000webhost and not sure if it is just that it was free or not.

**Comment by mcmuffindk** [comment]
I think it is because of your host. I have my app on my Raspberry Pi 3 and it is super fast in loading speeds

**Comment by RedSparr0w** [comment]
There has been a lot of problems hosting this on 000webhost and other free web hosting.

I would suggest finding a new host.
