### ISSUE TITLE
Obtaining Steam Guard Mobile Authenticator Status?

### ISSUE THREAD

**Issue by AngelTs** [SmItH197/SteamAuthentication#209]
I can't find a way to obtain that info via steamauth.
For example "file_get_contents(...)" not contain that data!

**Comment by BlackCetha** [comment]
SteamAuth itself can't provide that information. You will have to make a request to the steam api yourself.
Have a look at this endpoint: https://lab.xpaw.me/steam_api_documentation.html#IEconService_GetTradeHoldDurations_v1
