### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by lotfiuser** [SmItH197/SteamAuthentication#213]
![image](https://user-images.githubusercontent.com/5274016/37880219-3b1375ba-3085-11e8-995a-50f517771977.png)

**Comment by SmItH197** [comment]
More info please!!!!!

If you're referring to the HTTPS error this is a problem with your certificate. The domain on your certificate is showing as *.we hosting.com not justairdrop.com

**Comment by lotfiuser** [comment]
its not taking me to home page its taking me to that page
