### ISSUE TITLE
demo dont work

### ISSUE THREAD

**Issue by robotrono** [SmItH197/SteamAuthentication#216]
in this moment dont work the demo, i cant login, why?

**Comment by bman46** [comment]
Try now, I think the steam API may have been down. Also, did you get any errors when trying to login?

**Comment by bman46** [comment]
Solved in issue #217, Valve changed to HTTPS.

**Comment by robotrono** [comment]
I get some times "Endless redirection!"

**Comment by bman46** [comment]
please copy and paste the error output and post it here.

**Comment by bman46** [comment]
@vidit-agarwal re-download the newest version of the library or see pull request #218 and replicate those changes.
