### ISSUE TITLE
userInfo Not Working

### ISSUE THREAD

**Issue by frkncck** [SmItH197/SteamAuthentication#221]
I included userInfo.php. 
_$_SESSION['steam_steamid']_ is working but $steamprofile['steamid'] not working and others(avatar, name etc.).

                    if(isset($_SESSION['steamid'])){
                      include 'steamauth/userInfo.php';
                      echo $steamprofile['steamid']; // this is not showing
                    }

**Comment by SmItH197** [comment]
Are you getting any error messages?

**Comment by frkncck** [comment]
@SmItH197 no error message.

**Comment by bman46** [comment]
what version of steam with do you have?

**Comment by bman46** [comment]
*Steamauth

**Comment by BlackCetha** [comment]
You could try increasing the verbosity level to get more information. 
Documentation is here: http://php.net/manual/en/function.error-reporting.php

**Comment by frkncck** [comment]
I found the problem. allow_url_fopen is disabled in php.ini. So file_get_contents not working. I will contact with my hosting provider.

**Comment by SmItH197** [comment]
Glad to hear you found the source of the problem.
