### ISSUE TITLE
Question about "login button style"

### ISSUE THREAD

**Issue by mrc4tt** [SmItH197/SteamAuthentication#234]
Hi.

Sorry, if it's wrong to ask here.

I will hear, about it's possible to change the "login button style" to be.
Like this one (as example) >>
![](https://i.gyazo.com/398b4ee42159162bc89bfefcee83c0a8.png)

Without it needed to be: 
![](https://camo.githubusercontent.com/bc810ec0615dae65aae384e8e9b3cd7a2f5aa208/68747470733a2f2f737465616d636f6d6d756e6974792d612e616b616d616968642e6e65742f7075626c69632f696d616765732f7369676e696e7468726f756768737465616d2f736974735f30322e706e67)

Thanks!

**Comment by RedSparr0w** [comment]
You could modify these lines [here](https://github.com/SmItH197/SteamAuthentication/blob/master/steamauth/steamauth.php#L10-L12).

But as per the ["Steam Web API Documentation"](https://steamcommunity.com/dev) they prefer you use the specified style:
[![image](https://user-images.githubusercontent.com/7288322/47115201-51a02580-d2ba-11e8-8091-c61a102a4c2a.png)](https://steamcommunity.com/dev)

**Comment by mrc4tt** [comment]
Thanks! ;)
