### ISSUE TITLE
No OpenID Server found at https://steamcommunity.com/openid

### ISSUE THREAD

**Issue by Livaco** [SmItH197/SteamAuthentication#239]
Whenever i try to login to my website, the text in the title appears. No other person is getting this, and it's only me (Tested this with 2 other people, one from the same town), any idea at all as to what this is? Been going on for over 3 days now.

**Comment by bman46** [comment]
Just to verify, you can ping steamcommunity.com and when you go to the [link](https://steamcommunity.com/openid), it downloads a file.

**Comment by Livaco** [comment]
Yep. Worked fine before but now just not working at all.

**Comment by bman46** [comment]
do you have any logs that report an error?

**Comment by Livaco** [comment]
What do you mean by that?

**Comment by bman46** [comment]
On the server, there are no errors showing up on the log file that it generates.

**Comment by Livaco** [comment]
No I don't believe so.

**Comment by bman46** [comment]
hmm, if you have any other computers in you LAN, will it work on them?

**Comment by Livaco** [comment]
Not hosting it LAN, hosting with 000webhost. Domain is livaco.tk.

**Comment by bman46** [comment]
ah, 000webhost isn't a very good host and has had a reputation for having issues with this library for some reason. (#172 #202 #121)

**Comment by Livaco** [comment]
It can't be the host since other people can use the login system just fine.

**Comment by bman46** [comment]
Possibly, but given its track record, I wouldn't trust it. Anyway, try a different computer in your network -- I'm trying to rule out the issue of it being network or client related.

**Comment by Livaco** [comment]
Just tried to sign it and it worked fine. Not sure what happened but something did something. Going to keep this issue open in case it's just a one time miracle. Thanks for your efforts @bman46. I appreciate it.
