### ISSUE TITLE
No OpenID Server found at https://steamcommunity.com/openid

### ISSUE THREAD

**Issue by jlagaddi** [SmItH197/SteamAuthentication#241]
Done everything I could think of........Please help....

**Comment by bman46** [comment]
could not replicate with the latest version of SteamAuth. 
What have you tried already and have you tried updating the steamauth folder?

**Comment by RedSparr0w** [comment]
There is already 3 other issues open with the same title, please close this and comment on one of them.
#237 
#239 
#240 

Also if you could please try some of the suggested fixes in those threads: https://github.com/SmItH197/SteamAuthentication/issues/237#issuecomment-439696757
