### ISSUE TITLE
URL is currently unable to handle this request. HTTP ERROR 500

### ISSUE THREAD

**Issue by Jabbers99** [SmItH197/SteamAuthentication#245]
**Steps to Reproduce;**
- Click 'sign in with steam'
- Login

**Expected outcome:**
- You get redirected back to the website, logged in 

**Actual outcome:**
- You get redirected back to the website, with an error, not logged in
http://my.name.is.jabbe.rs/4i1tn.png

**Comment by BlackCetha** [comment]
Status code 500 is for "Internal server error", which is probably caused by a error in your own script. Check your PHP/webserver logs.
