### ISSUE TITLE
Stuck at ?login l Same with ?logout

### ISSUE THREAD

**Issue by Livaco** [SmItH197/SteamAuthentication#246]
Tried looking at other issues, but nothing in them seems to work. My config file is all configured correctly, and nothing else seems to be happening. I've tried loading older versions that worked before, updating it, using session_start(), and even modifying the files themselves. Nothing worked.
My website is: http://www.livaco.tk/ if anyone needs it.

If anyone knows what's happening that would be great!

**Comment by bman46** [comment]
When I click on the login button it redirects to http://www.livaco.tk/?login which I don't believe would be a page on your webserver. Can you please post the code that you used for the button. It should call the `loginbutton();` function.

**Comment by bman46** [comment]
also, ? represents a get request to that page and since there is *probably* nothing to handle it, it ignores it.

**Comment by Livaco** [comment]
`<div class="item"><a href="?login"><i class="sign in icon"></i>Sign In</a></div>`
I was using this code on my test server with the exact same setup, and it worked fine. No issues at all. steamauth.php should be handling the GET request to login since it's being [required](https://www.php.net/manual/en/function.require.php) before the button even gets made.

**Comment by bman46** [comment]
It will work if you use http://www.livaco.tk/steamauth/steamauth.php?login but since there is no handler on any other page for that it wont work.

**Comment by Livaco** [comment]
Odd, how would I implement that into my other webpages then? Like i said i'm calling the needed `require 'steamauth/steamauth.php';` so I would've assumed it would've worked?

**Comment by bman46** [comment]
Did you include the form part? https://github.com/SmItH197/SteamAuthentication/wiki/Creating-A-Custom-Logout-Button

**Comment by Livaco** [comment]
You can do either a link **or** form button. I did the links, but according to that it should work either way.

**Comment by bman46** [comment]
Try the form version instead then.

**Comment by Livaco** [comment]
That didn't work, but I've just simply done this `<div class="item"><a href="steamauth/steamauth.php?login"><i class="sign in icon"></i>Sign In</a></div>` and it seems to be working. I'm aware its not the best way to do it, but honestly I just want to get this website running (I spent a while making this new version so i'm a really annoyed from this). Thanks for your help.

**Comment by bman46** [comment]
Ok, no problem.

**Comment by RedSparr0w** [comment]
not sure if you figued this out yet or not, but all you need is:
```php
<?php
require_once ('steamauth/steamauth.php');
?>
```
**At the top** of each of your pages, or in your `header.php` or whatever you have named it.
Either way this file needs to be included/required on each page before anything else for the `?login` or `?logout` to work.

_If it's not at the top of the page the redirect won't work_
