### ISSUE TITLE
Undefined offset 0

### ISSUE THREAD

**Issue by ProfessorBoogie** [SmItH197/SteamAuthentication#250]
For some reason everytime i load on to my website i am given these errors:
![githubyeet](https://user-images.githubusercontent.com/52523255/60682892-0b4c2000-9e63-11e9-8042-7c0e20792c42.jpg)

the file 1.php is my index.php. 

here are my lines of code:
![image](https://user-images.githubusercontent.com/52523255/60644868-47e92e80-9e05-11e9-8201-72c4da0c3dab.png)
Someone please help me

**Comment by RedSparr0w** [comment]
It looks like you are trying to `include/require` `userInfo.php` before the user is logged in.

**Edit:**
Also on another note, It seems you aren't loading `steamauth.php` at the top of your file, otherwise you shouldn't be getting that first error.

**Comment by ProfessorBoogie** [comment]
> 
> 
> It looks like you are trying to `include/require` `userInfo.php` before the user is logged in.
> 
> **Edit:**
> Also on another note, It seems you aren't loading `steamauth.php` at the top of your file, otherwise you shouldn't be getting that first error.

How would i go about fixing that in the code?

**Comment by RedSparr0w** [comment]
Check if the user is logged in before including the file.

Checkout the `demo.php` file for more info.

**Comment by ProfessorBoogie** [comment]
> 
> 
> Check if the user is logged in before including the file.
> 
> Checkout the `demo.php` file for more info.

I had done this, it still doesnt work. 

<!DOCTYPE html>

<?

    require 'steamauth/steamauth.php';
    require 'steamauth/userInfo.php';
    
    
    {
        $id = $_SESSION['steamid'];  
    }
?>

**Comment by RedSparr0w** [comment]
**Edit:** Removed Info

Gambling sites are not supported by this library, which your site is one of, based on that code.
>I nor Steam condone the use of this library for the purpose of gambling sites. Any sites that use this library for this purpose violates their API agreement and will receive notices from Steam to cease operations.
>
>Read more here: http://store.steampowered.com/news/22883/
>
>By downloading this library you agree that you will not use it for any gambling or illegal activity.

https://github.com/SmItH197/SteamAuthentication#gambling-sites
