### ISSUE TITLE
Logout site

### ISSUE THREAD

**Issue by BigSeeProduction** [SmItH197/SteamAuthentication#30]
Does not work. Removing the dot before the header works!

**Comment by BlackCetha** [comment]
It seems i got to rework this thing. But your solution directs to the web page root, so it causes new problems itself.

**Comment by BigSeeProduction** [comment]
jeah i know but it works^^

**Comment by BigSeeProduction** [comment]
Just saying but in the settings.php there is a comment at the $logout_page which says "from the root folder of your website" so...?

**Comment by BlackCetha** [comment]
Basically, that means "from the directory the steamauth folder is in"
Gonna re-do the system anyways, give me a second.

**Comment by SmItH197** [comment]
Alright, thanks guys! Sorry I'm not very responsive but I'm in the middle of exams right now. :(

**Comment by BlackCetha** [comment]
This should be fixed in my pull request.
