### ISSUE TITLE
Proper way of using this with CodeIgniter?

### ISSUE THREAD

**Issue by PureTryOut** [SmItH197/SteamAuthentication#36]
First of all, great work, it works great!
Well it does in a standalone application.

I'm trying to get this to work with CodeIgniter, and I sort of did it but can only use the session variables ($_SESSION['steamid'], etc) and not the $steamprofile variable.

I've put the files in the "helper" directory, renamed "steamauth.php" to "steamauth_helper.php", and made it auto load. Then I copied the code from "userInfo.php" and pasted it in "steamauth_helper.php" inside the "if($openid->validate())" section (so it is run when logged in successful).

Like I said: it properly shows the button, logs me in and everything, but I can only use the session variables.
Is it maybe possible to make a proper hook or library from this that I can use? Yes it works but it feels kinda like a hack which I rather not do when possible.

**Comment by SmItH197** [comment]
Sorry, but I have never used CodeIgnitor so I am not sure how I would go about doing that :/

**Comment by PureTryOut** [comment]
Aah well no problem. You should look into it though, it's great, and very popular!

I'll just continue with the session variables then.

**Comment by SmItH197** [comment]
Yeah I will take a look into it and see if I can fix it. But no promises though! ;)
