### ISSUE TITLE
I need help.

### ISSUE THREAD

**Issue by aldrin21** [SmItH197/SteamAuthentication#38]
![captura](https://cloud.githubusercontent.com/assets/11455461/6646508/a86fabea-c997-11e4-83d7-e88f418209b8.JPG)
Truth is not about any of this, I need to know how to create ?login page: example: http://bensmith.in/steam/?login

**Comment by SmItH197** [comment]
If you mean the login page on steam, that can't be changed. All authentication takes place on steam's servers. So if you want to email Valve and ask them to change it, feel free ;)
