### ISSUE TITLE
I need help.

### ISSUE THREAD

**Issue by aldrin21** [SmItH197/SteamAuthentication#39]
What is wrong?

![captura](https://cloud.githubusercontent.com/assets/11455461/6649422/a41adc62-c9bb-11e4-9fe7-23444a14b4b6.JPG)
![captura2](https://cloud.githubusercontent.com/assets/11455461/6649423/a41f240c-c9bb-11e4-8cd8-936ded7976a8.JPG)

**Comment by aldrin21** [comment]
done.

**Comment by SmItH197** [comment]
Guessing the domain name wasn't entered correctly
