### ISSUE TITLE
Session Timeout

### ISSUE THREAD

**Issue by Prawx** [SmItH197/SteamAuthentication#41]
I'm having a problem where the session times out extremely fast. How can I increase session time of SteamAuth or make the session permanent? I understand you aren't obligated to give support but this really is a simple thing that nobody on Stackoverflow wants to help me with.

**Comment by BlackCetha** [comment]
You could've googled it first...
http://stackoverflow.com/questions/8311320/how-to-change-the-session-timeout-in-php
http://stackoverflow.com/questions/520237/how-do-i-expire-a-php-session-after-30-minutes

**Comment by SmItH197** [comment]
Done, thanks BlackCetha.

**Comment by Prawx** [comment]
Where do I add this code, though? I tried adding it in steamauth.php but no luck..

**Comment by BlackCetha** [comment]
![github](https://cloud.githubusercontent.com/assets/7271868/6803888/ddcaf104-d23a-11e4-8cf9-e5e49358e281.png)

You need to put the code before starting the session, logically.

*Code is coincidence.*
