### ISSUE TITLE
Storing steamid in mysql

### ISSUE THREAD

**Issue by Mayloudin** [SmItH197/SteamAuthentication#42]
is there any way i can get the steamid of a user and store it in my mysql database as soon as he logs in?

**Comment by BlackCetha** [comment]
Uhm... the $_SESSION['steamid'] variable is accessable at any time a user is logged in.
It should be fairly easy to store them in your db.

*Just a quick reminder: This is a libarary for steam-logins, not a general php-questionboard*

**Comment by SmItH197** [comment]
As BlackCetha has said, you can use $_SESSION['steamid'] once a user has logged in. It should be quite easy to add a function in steamauth.php to store/check the users steam ID. But that is not the purpose of this project.

Issue closed.
