### ISSUE TITLE
Assistanc needed - Var passthrough

### ISSUE THREAD

**Issue by hirsty** [SmItH197/SteamAuthentication#43]
Hey,

Wonderful plugin youve got here...just curious, what is the best way to get dynamic vars to passthrough after account log in? such as if my url var was:

$url = "http://www.example.com/index.php?status=".$dbstatus

where $dbstatus would be fetched dynamically from a DB on a per user basis.

**Comment by hirsty** [comment]
So it would stay in my url after :)

**Comment by BlackCetha** [comment]
This is *NOT* a forum for PHP-Newbies *NOR* a questionboard. "Issues" are ment to keep track of bugs and other mistakes directly in the code.
I am not going to answer your question as this entire "issue" will not be displayed any longer, so it would not help anyone else.
Consider reading the PHP manual regarding the $_GET variable - and please close this.

**Comment by SmItH197** [comment]
A good start would be to look at GET variables as BlackCetha suggested, then set the return URL to meet your needs.
