### ISSUE TITLE
Remember me login

### ISSUE THREAD

**Issue by Maarethyu** [SmItH197/SteamAuthentication#45]
Hi ^^
I need a "remember me login" feature on my website, can you help me ?

**Comment by BlackCetha** [comment]
Not really.
SteamAuth uses Sessions. Theese always stay active as long as specified in your PHP-settings.

You might want to have a look at this:
http://stackoverflow.com/questions/8311320/how-to-change-the-session-timeout-in-php#8311400

You could dynamically change the lifetime of the client-side cookie based on wether or not the user selected to remember his login.

**Comment by Maarethyu** [comment]
Well i'm a begginer and i don't know what to do
I need to relog everytime i close my website tab so i don't think the lifetime will change something ?
