### ISSUE TITLE
use in wordpress

### ISSUE THREAD

**Issue by mTorkaman** [SmItH197/SteamAuthentication#46]
hi ,
sry for bad english .
i need use your SteamAuth in wordpress pls tell me how to use ?

**Comment by BlackCetha** [comment]
You can use a plugin like this: https://wordpress.org/plugins/oa-social-login/

It is not possible to get this library to work with wordpress without having to re-code a lot of the code.

**Comment by mTorkaman** [comment]
i see this plugin and use one time but this plugin just for login from steam but .
this site use a good plugin http://irandota2.com/
when you login to this site can see your information and they are give you a trade link
