### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by Mitch8910** [SmItH197/SteamAuthentication#47]
Hi there! This code is exactly what I need for my website I'm grateful that you have made it available, though as of now, I can't get it to work. I have followed all the instructions and have come to no fruition. 
With everything set as I believe it should be, when I test my site I get just a blank page. 
I don't believe this is an error on my side, but if it is, sorry for reporting it as an error in code.

If you wish to check my files to see this is a new coding error, here they are:

Settings.PHP : http://gyazo.com/5ad364462a8be46ea0cc91472d97f08f
DreamWeaver File & Code : http://gyazo.com/c0441de71442cf68b53323d6b10e0385
Result when run : http://gyazo.com/7bc06fb723bb1281681358b0f4902c36

I also tested the demo code, and the button and steam login also didn't work.
Demo.html : http://gyazo.com/2e6250192a7e8d3c417e3359bb42e8e0

The rest of the .PHP files are unchanged.

**Comment by SmItH197** [comment]
Its because the code is in a html file not a .php file, therefore the php isn't being executed

**Comment by Mitch8910** [comment]
Wow, thanks for the fast reply. I will try that, thanks.

**Comment by Mitch8910** [comment]
I got it to work in a .php file, thanks. Making my Dreamweaver .html file into .php messed it up though. 
I don't want to bother you, but I've been doing research and can't find the answer. It is possible to use this .php script in a .html file? If not, I'm very confused, seeing as most websites are in HTML, how else can I use this script? Will I have to make a website in PHP?

**Comment by Mitch8910** [comment]
*turning my HTML file into a PHP file so I could use the script kept all the text on the page, but it lost the layout and special effects (scrolling images) and just left a white background with text and the "Sign in through Steam button". Am I just doing something wrong to make this happen? If yes you don't have to tell how to fix it if you don't want to, but I want to know if it's possible to make it work.

**Comment by BlackCetha** [comment]
If you only wrap the script in <?php tags, it will work. You can have a look at a good intro to php here: http://w3schools.org

**Comment by SmItH197** [comment]
Any web page that has PHP code inside it will have to have a .php extension. Just rename your example.html to example.php, any HTML code inside it will render normally and the PHP code inside the <?php and ?> tags will still execute. Any pages inside your website that does not have PHP in the file can stay .html files.

Look at the [demo.php file](https://github.com/SmItH197/SteamAuthentication/blob/master/demo.php).
You will notice that it looks and is layed out exactly like an html file. But the .php extension allows any code inside the <?php ?> tags to be executed as php.

Recap: 
* Renaming your page.html to page.php won't make any difference to the HTML displayed. 
* If you want to use PHP just put your PHP code inside the <?php ?> tags. Look at the [example.php file.](https://github.com/SmItH197/SteamAuthentication/blob/master/example.php)

**Comment by Mitch8910** [comment]
Great, Thanks guys! I really appreciate the help and fast responses. I have to go now, but I will try to make it work tomorrow and see how I go. 

Cheers.

**Comment by SmItH197** [comment]
No worries!
