### ISSUE TITLE
steam persona, possible mysql injection

### ISSUE THREAD

**Issue by geri43** [SmItH197/SteamAuthentication#48]
It's just a note, but if someone updates the steam persona directly in a mysql_query (without using mysql_real_escape_string like me :( ), if the persona contains an ' mark, it'd override everyone's persona in the database, or even worse.

**Comment by BlackCetha** [comment]
This should be fixed with https://github.com/BlackCetha/SteamAuthentication/commit/00b9abfdfa45dbe322337c2bf1b631b5a50d419c

**Comment by SmItH197** [comment]
Merged, thanks. Will create a new release.
