### ISSUE TITLE
Mysql databse issue in userInfo.php

### ISSUE THREAD

**Issue by camkaley** [SmItH197/SteamAuthentication#50]
Hey i recently found thius and tried to get it all working and whatnot, i managed to get it so you can click "Login with steam", then login from the demo page, but when after i click "Log In" from the steam page it takes a decent ammount of time to load and then gives me this error:

Warning: file_get_contents(http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=[REMOVED_BY_SmItH197]&steamids=76561198181922383): failed to open stream: Connection timed out in /home/csgomark/public_html/steamauth/userInfo.php on line 4

Deprecated: mysql_real_escape_string(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /home/csgomark/public_html/steamauth/userInfo.php on line 9

Warning: mysql_real_escape_string(): Access denied for user 'root'@'localhost' (using password: NO) in /home/csgomark/public_html/steamauth/userInfo.php on line 9

Warning: mysql_real_escape_string(): A link to the server could not be established in /home/csgomark/public_html/steamauth/userInfo.php on line 9

If you could tell me what im doing wrong i would really apprecite it as i cant find the answer anywhere else and i am fairly new to this.

Also i am using a free hosting site to host this - X10hosting - They support mysql and have databases and stuff, sorry for being a pain...

Thanks,
Cam

**Comment by BlackCetha** [comment]
You should remove your API-Key.

The file_get_contents error is caused by the steam-api. It sometimes takes too much time to react, or it was down while you tested. This doesn't happen too often, but is still disgusting for valve.

Sometimes hosting providers disable the use of file_get_contents, meaning that you have to use a workaround as purposed here: https://github.com/SmItH197/SteamAuthentication/pull/34/files

mysql_real_escape string is used to prevent sql-injection (http://www.w3schools.com/sql/sql_injection.asp). It is depricated, but since the newer function requires a connected database we cannot use it.

The only thing i have no idea about what is causing it is
`Warning: mysql_real_escape_string(): Access denied for user 'root'@'localhost' (using password: NO) in /home/csgomark/public_html/steamauth/userInfo.php on line 9`

Did you try to link mysql_real_escape string? Did you try to connect to a database in userInfo.php?

**Comment by camkaley** [comment]
Firstly may i say thanks for the quick answer!

Secondly, i have left all files default except for the settings.php file that i edited to my liking, i have not attempted to connect to a database (Not on purpose atleast) seeing as i havent changed the file. I dont know if i was supposed to edit other files, if so i would appreciate it if you pointed out where!

Finally, the link you sent, i am not 100% sure what to do with that new code.... It would really help if you could explain...

Once again, sorry for being a pest and i appreciate your patients towards the situation.

Thanks,
Cam

**Comment by BlackCetha** [comment]
It's OK that you ask.

Add that into your userInfo.php file right after the include:
`function url_get_contents ($Url) {
    if (!function_exists('curl_init')){ 
        die('CURL is not installed!');
    }
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $Url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $output = curl_exec($ch);
    curl_close($ch);
    return $output;
}`
And exchange `file_get_contents()` with `url_get_contents()`.

Report back if it does work.

**Comment by camkaley** [comment]
Ok, i am not 100% sure i edited the files correctly as there is another error:

Parse error: syntax error, unexpected ',' in /home/csgomark/public_html/steamauth/userInfo.php on line 48

Here are the files in a pastebin:

settings.php - http://pastebin.com/Q4DZuwRe
userInfo.php - http://pastebin.com/0U8m0tsp

(You can see the extra code at the bottom of the file for both files)

If you can spot any problems please let me know... once again sorry for bothering you so often.

Thanks,
Cam

**Comment by camkaley** [comment]
BTW i am also having a look and trying to work it out, not just relying on you to do it all for me ;)

**Comment by SmItH197** [comment]
What's the `@@ -34,3 +34,5 @@` on line 48? Try deleting it

**Comment by camkaley** [comment]
Update: New error - Parse error: syntax error, unexpected end of file in /home/csgomark/public_html/steamauth/userInfo.php on line 54

**Comment by camkaley** [comment]
No idea and i did delete it!

**Comment by camkaley** [comment]
Now im pretty sure there is no line 54...

**Comment by camkaley** [comment]
I am so sorry guys, i dont mean to be such a pest and im sure you have more important things to do, but i can give you the website itself so you can see the errors that come up

- http://csgomarket.x10host.com/test.php

**Comment by SmItH197** [comment]
No worries! And heck its a Friday afternoon, so I have nothing to do ;)

**Comment by camkaley** [comment]
Haha thanks mate, i really really appreciate it!

**Comment by camkaley** [comment]
You find anything? I cant seem to do anything to fix this "Unexpected end of file" error...

**Comment by SmItH197** [comment]
try using this for UserInfo.php: http://pastebin.com/Sxti9SD0
try using this for settings.php: http://pastebin.com/5CGRVhVL

**Comment by camkaley** [comment]
Ok, changed the code....

- Taking ages to redirect after login on steam website...
- Same error as before...

Deprecated: mysql_real_escape_string(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /home/csgomark/public_html/steamauth/userInfo.php on line 9

Warning: mysql_real_escape_string(): Access denied for user 'root'@'localhost' (using password: NO) in /home/csgomark/public_html/steamauth/userInfo.php on line 9

Warning: mysql_real_escape_string(): A link to the server could not be established in /home/csgomark/public_html/steamauth/userInfo.php on line 9

**Comment by camkaley** [comment]
I have no idea what this root@localhost problem is, i have looked everywhere and cant find a fix.

Was i supposed to make a mysql database?

**Comment by camkaley** [comment]
I am starting to assume it is my host, blocking some php code for security reasons?

**Comment by SmItH197** [comment]
are you going to be inserting the data into a database?

**Comment by SmItH197** [comment]
just read a forum thread (https://x10hosting.com/community/threads/problem-with-file_get_contents.176508/), seems file_get_contents is disabled on your hosting.

**Comment by BlackCetha** [comment]
Thats why i told him to use cURL. It should be working with that.

**Comment by camkaley** [comment]
Dammit, im so sorry for wasting your time

**Comment by camkaley** [comment]
Do you guys know of a good, fairly cheap host that would allow these permissions?

**Comment by SmItH197** [comment]
what country do you live in?

**Comment by camkaley** [comment]
Australia

**Comment by BlackCetha** [comment]
And how much do you want to spend?

**Comment by BlackCetha** [comment]
Australia is always kinda tricky regarding hosts and basically everything regarding the internet...
Also, if youre going to make the site international, you might want to get a hoster located in europe/america. Theese would be cheaper.

**Comment by camkaley** [comment]
I was going to say, i am not really fussed about where the site is hosted, just if you know of any good cheap ones, if not i can have a look.

**Comment by SmItH197** [comment]
I used http://hostpresto.com (UK based). £24.00 a year, service is really good

**Comment by camkaley** [comment]
Wow that is cheap, ok awesome, thanks mate!

**Comment by camkaley** [comment]
And just to clarify, you know they will allow all the needed PHP permissions?

**Comment by SmItH197** [comment]
I used them for over 2 years, worked a charm!

**Comment by camkaley** [comment]
Thank you mate, i really appreciate it, im sorry i wasted a load of your time, i really appreciate the help, thanks!

**Comment by BlackCetha** [comment]
I gotta admit, i didnt test the injection fix yet because i expected mysql_real_escape_string like in the documentation... Since it throws that error, I'll have a look at it.

Close?

**Comment by camkaley** [comment]
Close, thanks guys!

**Comment by BlackCetha** [comment]
No problem. If you have any further questions, feel free to add me on steam (http://steamcommunity.com/id/blackcetha)

**Comment by SmItH197** [comment]
Closed :)

**Comment by SmItH197** [comment]
Switch to #51, to discuss the mysql real escape string error.
