### ISSUE TITLE
mysql_real_escape_string() error

### ISSUE THREAD

**Issue by SmItH197** [SmItH197/SteamAuthentication#51]
Following errors:

`Deprecated: mysql_real_escape_string(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead in /home/public_html/steamauth/userInfo.php on line 9`

`Warning: mysql_real_escape_string(): Access denied for user 'root'@'localhost' (using password: NO) in /home/public_html/steamauth/userInfo.php on line 9`

`Warning: mysql_real_escape_string(): A link to the server could not be established in /home/public_html/steamauth/userInfo.php on line 9`

**Comment by BlackCetha** [comment]
As @trurascalz suggested, we should roll back the mysql_real_escape string as this is a library and it should be down to the user. Additionally, it could break the data returned.

**Comment by SmItH197** [comment]
Reverted pull request, closed.
