### ISSUE TITLE
file_get_contents returning "Connection timed out"

### ISSUE THREAD

**Issue by excusemyluck** [SmItH197/SteamAuthentication#53]
Besides the mysql errors you have in 50 other issues probably, I keep getting this one:

**Warning: file_get_contents(http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=<key>&steamids=<id>): failed to open stream: Connection timed out in /home/ibreakzo/public_html/libs/steamauth/userInfo.php on line 4**

If there is any known fix for this that I cannot seem to find (I have been doing hours of research, literally), **PLEASE** let me know.

Thank you and have a wonderful rest of your afternoon!

**Comment by excusemyluck** [comment]
For the file_get_contents, I used this(https://github.com/SmItH197/SteamAuthentication/pull/34/files) cURL variable of getting the users information, but it actually crashed my website multiple times and would just keep trying to get the information. It would give me a backend error on the site

**Comment by csgiveaway** [comment]
Have you entered your details into the settings?

**Comment by excusemyluck** [comment]
I have. All 5 have my own choices set

**Comment by SmItH197** [comment]
Looks like your using the same host as #50, it seems like the host has disabled file get contents. Will look at a work around later.

**Comment by excusemyluck** [comment]
Is there any host you do recommend that you know works?

**Comment by wortel538** [comment]
I use dot.tk (FreeNom) together with freehostingnoads.com, It is down some times a day, I use it alot, Its all free :D

**Comment by excusemyluck** [comment]
@wortel538 alright thank you for the help :D

**Comment by SmItH197** [comment]
Looks like a host issue, closed.
