### ISSUE TITLE
How to make the login / logout page return to a variable url

### ISSUE THREAD

**Issue by Partixel** [SmItH197/SteamAuthentication#56]
e.g.

test.com?test=1

test.com?test=2

**Comment by SmItH197** [comment]
Go to `settings.php` and set `$steamauth['loginpage']` to the page you want.

For example:
`$steamauth['loginpage'] = "index.php?test=1"`

**Comment by Partixel** [comment]
But if the ?test=1 part is variable, e.g. in php:

$var = rand(1, 100);
$url = "test.com?test=" . $var

and I want it to return to the same page with test being the same number

**Comment by Partixel** [comment]
I tried:
		$steamauth['logoutpage'] = "?type=" . $_GET["type"] . "&script_id=" . $_GET["script_id"];
		$steamauth['loginpage'] = "?type=" . $_GET["type"] . "&script_id=" . $_GET["script_id"];

before the login/logout button but that didn't work

**Comment by BlackCetha** [comment]
The login and logout redirection is relative to your SteamAuth directory. So just put "/../" infront of what you have written there.

**Comment by SmItH197** [comment]
The problem is it doesn't carry through the $_GET variables

**Comment by Partixel** [comment]
Yeah, it doesn't redirect back to the page with the same $_GET variables, even though the logoutpage / loginpage is set to it.

**Comment by SmItH197** [comment]
Currently messing around with it, will try and work out a way

**Comment by Partixel** [comment]
Thanks :)

**Comment by MeLlamoPablo** [comment]
Hey, @Partixel. This may be too late for you probably, but on my fork I've solved this issue. You can check out my pull request #66.

This:
```php
echo steamlogin("test=".$test.);
```
should do the trick for you.

**Comment by Partixel** [comment]
Thanks! :)

**Comment by SmItH197** [comment]
As @MeLlamoPablo pointed out, this has been added in the latest release.
