### ISSUE TITLE
Login from a page that need initial value?

### ISSUE THREAD

**Issue by franrevoredo** [SmItH197/SteamAuthentication#57]
Hi i needed to implement a steam login in my webpage and this project solved my problems, but now i got an issue. It worked well in "static" pages but when i need to login from a page that need an initial "get value" like a search page it simply doesn't work. When i hit the login button the page ask me for a value to search and doesn't proceed to the login redirect.

 The problem is that the button calls a "?login" form action and it clear the get values of the actual page. 

Thanks!

PD: I'm using 2.1.3 release.

**Comment by BlackCetha** [comment]
You could redirect to a new php file that calls `steamlogin()` directly and passes through your GET parameters.

**Comment by BlackCetha** [comment]
You could do it like this: https://gist.github.com/BlackCetha/eb0ba62c016f4501de87
Note that it is not tested.

**Comment by franrevoredo** [comment]
Thanks, i will try that and let you know.

**Comment by franrevoredo** [comment]
mmm i tried this but it didnt work. I cant successfully override the 'loginpage' value, and when i redirect the button to the other page that only gets the "GET" values and execute steamlogin() it only shows the button, i would need a way to force the page to go to the steam login page.

**Comment by franrevoredo** [comment]
Well i solved the problem, i read a session var in the steamlogin() function that i previously created in the login page that captures the actual login page with a "$_SESSION['login_page'] = basename($_SERVER['PHP_SELF']);" so i can redirect the page after the steam redirection.

Thanks!
