### ISSUE TITLE
"Couldn't connect to host"

### ISSUE THREAD

**Issue by Wikiter** [SmItH197/SteamAuthentication#59]
You did really good job there. Good work :), but unfortunately it doesn't work for me :(.
I followed your instructions and used example.php as my index.php. When I click "Sign in through steam" it doesn't redirect to the steam page, but it shows me "Couldn't connect to host".
By the way, does SteamAuthentication use curl? Maybe that's the problem becouse my hosting doesn't  support it.

**Comment by SmItH197** [comment]
It uses file_get_contents, can you post a link?

**Comment by Wikiter** [comment]
My hosting's link? Sure, www.ugu.pl 
It is not english unfortunately. I'll try tommorow on the other hosting.

**Comment by SmItH197** [comment]
Sorry I meant a link to your site

**Comment by Wikiter** [comment]
http://csgosolo.ugu.pl

**Comment by wortel538** [comment]
How did you get google ads?
Op 11 mei 2015 00:48 schreef "Wikiter" <notifications@github.com>:

**Comment by Wikiter** [comment]
These are not my ads. My hosting included it. I don't use that hosting any longer.

**Comment by SmItH197** [comment]
Does it work on your new host?

**Comment by Wikiter** [comment]
yes :D Now it works. You can close that thread. Thank you very much for the support.
