### ISSUE TITLE
Warning: session_start() Cannot send session cache limiter - headers already sent

### ISSUE THREAD

**Issue by wortel538** [SmItH197/SteamAuthentication#60]
Hi Guys, If I try to do:
```php
<?php
    require ('steamauth/steamauth.php'); 
	include ('steamauth/userInfo.php');
	if(!isset($_SESSION['steamid'])) { }
	else {
	$userdbfile = file('userfiles/' . $steamprofile['steamid'] . '.txt');	
	}
?>
```
I get:
Warning: session_start() [function.session-start]: Cannot send session cache limiter - headers already sent (output started at %path%/public_html/beta/index.php:2) in %path%/steamauth/steamauth.php on line 2

 (%path is replaced with the path..)

Thanks for everything, Keep up the work!

**Comment by SmItH197** [comment]
Try Moving `include ('steamauth/userInfo.php');` to your `else` statement.

**Comment by wortel538** [comment]
Even after doing this, I still get it

(Woah, Thanks for the fast response!)

**Comment by SmItH197** [comment]
Put `session_start();` After `<?php`

**Comment by SmItH197** [comment]
Have you changed steamauth.php at all?

**Comment by SmItH197** [comment]
Make sure that the very top of the `steamauth.php` file is the following:
```php
<?php
ob_start();
session_start();
```

**Comment by wortel538** [comment]
<?php
ob_start();
session_start();
require ('openid.php');
...

**Comment by wortel538** [comment]
I can replace the whole thing with the version on github, maybe it'll work?

**Comment by SmItH197** [comment]
What "thing"?

**Comment by BlackCetha** [comment]
Do you use the windows default editors? They tend to put one or two newlines at the beginning.

**Comment by wortel538** [comment]
I use notepad++, I replaced steamauth with that on this github, It didnt work either.

**Comment by BlackCetha** [comment]
Try the demo file. Does it work?

**Comment by wortel538** [comment]
That one works succesfully.

**Comment by wortel538** [comment]
I used SteamAuth before on this website. This time I got this error

**Comment by BlackCetha** [comment]
That means that it's not SteamAuth.php. Make sure there is really nothing infront of <?php in your file.
Try making a new file and copy-pasting the things between the PHP-tags.

**Comment by wortel538** [comment]
Is <!DOCTYPE html> a thing?

**Comment by SmItH197** [comment]
Make sure there is no whitespace at the top of the file.

**Comment by BlackCetha** [comment]
Yes, it certainly is.

**Comment by wortel538** [comment]
Woops... Thanks :D

**Comment by wortel538** [comment]
You can close it... Stupid me

**Comment by BlackCetha** [comment]
Technical background: PHP modifies the HTTP-headers to tell the browser how long it should keep the session cookie. The headers get send at first, before any of the HTML. Meaning if you write anything infront of it, it will close the headers and not be able to set the cookie lifetime.

**Comment by BlackCetha** [comment]
@SmItH197 Another thing: Is the demo page going to come back online somewhere soon?
Otherwise we could move it to github.io or my server.

**Comment by SmItH197** [comment]
I will try and get it back up this weekend. Sorry everyone about the downtime!
