### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by cymruu** [SmItH197/SteamAuthentication#61]
What is the license of the library?

**Comment by SmItH197** [comment]
May I ask why?

**Comment by cymruu** [comment]
I ask about license. I wonder if i can use it in commercial projects

**Comment by SmItH197** [comment]
Sent you a email.

**Comment by SmItH197** [comment]
For anyone interested in using this project commercially I would love to have a link to your site (out of curiosity) and I would appreciate it if you could link back to this repo on your site.

Thanks,
SmItH197
