### ISSUE TITLE
stuck on /?login

### ISSUE THREAD

**Issue by Mikize** [SmItH197/SteamAuthentication#63]
Hi, I put a login button in the index.php but it's doing nothing and get stuck on /?login.
It work on the example.php but not on the index.php

**Comment by SmItH197** [comment]
could you post the code your using in your index.php?

**Comment by Mikize** [comment]
simply 
<?php
if(!isset($_SESSION['steamid'])) {

steamlogin(); //login button

}  else {

include ('steamauth/userInfo.php'); //To access the $steamprofile array
//Protected content

logoutbutton(); //Logout Button
}     
?>

**Comment by SmItH197** [comment]
Put  
```php
require ('steamauth/steamauth.php'); 
```

after `<?php`

**Comment by Mikize** [comment]
It's at the very top of my page right avec the DOCTYPE

**Comment by SmItH197** [comment]
Could you post the very top of your file?

**Comment by Mikize** [comment]
<!DOCTYPE HTML>
<?php
    require ('steamauth/steamauth.php');  
    
	# You would uncomment the line beneath to make it refresh the data every time the page is loaded
	// $_SESSION['steam_uptodate'] = false;
?>
<html>

**Comment by SmItH197** [comment]
try removing `<!DOCTYPE HTML>`

**Comment by Mikize** [comment]
still not working

**Comment by SmItH197** [comment]
where does it get stuck? Before are after you login on the steam website?

**Comment by Mikize** [comment]
before

**Comment by SmItH197** [comment]
could you post you entire file? If example.php works then it suggests that there is something wrong with the file. Do you get any error messages or does it just hang?

**Comment by Mikize** [comment]
in a pastebin ?

**Comment by SmItH197** [comment]
or here

**Comment by Mikize** [comment]
<?php
    require ('steamauth/steamauth.php');  
    
	# You would uncomment the line beneath to make it refresh the data every time the page is loaded
	// $_SESSION['steam_uptodate'] = false;
?>
<html>
	<head>
		<title>United Gaming</title>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		
		<script src="/js/jquery.min.js"></script>
		<script src="/js/skel.min.js"></script>
		<script src="/js/skel-layers.min.js"></script>
		<script src="/js/init.js"></script>
		<noscript>
			<link rel="stylesheet" href="css/skel.css" />
			<link rel="stylesheet" href="css/style.css" />
			<link rel="stylesheet" href="css/style-xlarge.css" />
		</noscript>
	</head>
	<body class="landing">

		
			<header id="header" class="alt">
				<h1><strong><a href="">United Gaming</a></strong></h1>
				<nav id="nav">
					<ul>
						<li><a href="index.php">Accueil</a></li>
						<li><a href="/sourceban">Sourceban</a></li>
						<li><a href="/forum">Forum</a></li>
						<li><a href="/vip">VIP</a></li>
					</ul>
				</nav>
			</header>

		
			<section id="banner">
				</br></br></br></br></br><h2>United Gaming</h2></br></br></br></br></br></br>
			</section>
			
				<section id="one" class="wrapper style2 special">
					<div class="container">
					<header class="major">
						<h2>VIP</h2>
						<p>Découvrer nos avantages VIP !<p>
					</header>
						<h4>Avantages :</h4>
						<ul>
							<li>Slots réservés.</li>
							<li>Tag VIP dans le chat.</li>
						</ul>
						<?php
						if(!isset($_SESSION['steamid'])) {

							steamlogin(); //login button

						}  else {

							include ('steamauth/userInfo.php'); //To access the $steamprofile array
							//Protected content

							logoutbutton(); //Logout Button
						}     
						?>
					</div>
				</section>

		
			<footer id="footer">
				<div class="container">
					<ul class="icons">
						<li><a href="http://twitter.com/UnitedGamingFR" class="icon fa-twitter"></a></li>
					</ul>
					<ul class="copyright">
						<li>&copy; United Gaming</li>
					</ul>
				</div>
			</footer>

	</body>
</html>

**Comment by SmItH197** [comment]
weird, it works for me on my localhost. What host do you use?

**Comment by Mikize** [comment]
pulseheberg.com

**Comment by Mikize** [comment]
well it's in the directory /vip/

**Comment by Mikize** [comment]
Well apparently it works now don't know what I changed but thanks for the help
