### ISSUE TITLE
The login button doesn't work on my website, but works localhost

### ISSUE THREAD

**Issue by AwesomeTurtwig** [SmItH197/SteamAuthentication#67]
The title says most of my issue... I managed to set it up to work on my localhost using xampp. However when I upload it and click the login button, I return to the same url with "?login" tacked at the end (of the url). I am not sure what the issue is, I changed setting to redirect to my domain name (and not local host), but I am without a clue.

Here's some of my host's info: http://i.imgur.com/kpJWCEZ.png
And here's a link to my site, with the issue: http://potders.com/awesome-stats/

**Comment by AwesomeTurtwig** [comment]
I see someone else was having the same problem, but they closed their question and also wasn't sure what fixed it. This is the FULL php file that I am using for the login button.

http://pastebin.com/TdFeJuuS

**Comment by BlackCetha** [comment]
You need to include steamauth at the beginning of your script before any text output.

**Comment by AwesomeTurtwig** [comment]
Thanks BlackCetha, that seems to have fixed it! Such a simple mistake! Thanks so much!
