### ISSUE TITLE
Logging in problem

### ISSUE THREAD

**Issue by Sphagnum** [SmItH197/SteamAuthentication#70]
After logging in, this error always displayed (and it has a typo):
"Error: failed to fetch content form Steam. It may be down. Please, try again later."

...and the logout button is not displayed, so I have to comment out the "include('steamauth/userInfo.php'); line to get the logout button back once I've attempted to log in already.

**Comment by Sphagnum** [comment]
Fixed the logic that causes the lost Logout button.  Still not sure why login fails to get any info.

<?php
    //We make sure that the user has logged in before attempting to use the Steam API to avoid warnings and wasted resources.
    if(isset($_SESSION['steamid']))
    {
    	include("settings.php");
        if (empty($_SESSION['steam_uptodate']) or $_SESSION['steam_uptodate'] == false or empty($_SESSION['steam_personaname']))
        {
            //We mute alerts from the following line because we do not want to give away our API key in case file_get_contents() throws a warning.
            @ $url = file_get_contents("http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=".$steamauth['apikey']."&steamids=".$_SESSION['steamid']);
            if($url === FALSE)
            {
                echo('Error: failed to fetch content form Steam. It may be down. Please, try again later. <br>');
            }
            else
            {
                $content = json_decode($url, true);
                $_SESSION['steam_steamid'] = $content['response']['players'][0]['steamid'];
                $_SESSION['steam_communityvisibilitystate'] = $content['response']['players'][0]['communityvisibilitystate'];
                $_SESSION['steam_profilestate'] = $content['response']['players'][0]['profilestate'];
                $_SESSION['steam_personaname'] = $content['response']['players'][0]['personaname'];
                $_SESSION['steam_lastlogoff'] = $content['response']['players'][0]['lastlogoff'];
                $_SESSION['steam_profileurl'] = $content['response']['players'][0]['profileurl'];
                $_SESSION['steam_avatar'] = $content['response']['players'][0]['avatar'];
                $_SESSION['steam_avatarmedium'] = $content['response']['players'][0]['avatarmedium'];
                $_SESSION['steam_avatarfull'] = $content['response']['players'][0]['avatarfull'];
                $_SESSION['steam_personastate'] = $content['response']['players'][0]['personastate'];
                if (isset($content['response']['players'][0]['realname']))
                { 
    	            $_SESSION['steam_realname'] = $content['response']['players'][0]['realname'];
    	        }
    	        else
    	        {
    	            $_SESSION['steam_realname'] = "Real name not given";
                }
                $_SESSION['steam_primaryclanid'] = $content['response']['players'][0]['primaryclanid'];
                $_SESSION['steam_timecreated'] = $content['response']['players'][0]['timecreated'];
                $_SESSION['steam_uptodate'] = true;
                
                $steamprofile['steamid'] = $_SESSION['steam_steamid'];
                $steamprofile['communityvisibilitystate'] = $_SESSION['steam_communityvisibilitystate'];
                $steamprofile['profilestate'] = $_SESSION['steam_profilestate'];
                $steamprofile['personaname'] = $_SESSION['steam_personaname'];
                $steamprofile['lastlogoff'] = $_SESSION['steam_lastlogoff'];
                $steamprofile['profileurl'] = $_SESSION['steam_profileurl'];
                $steamprofile['avatar'] = $_SESSION['steam_avatar'];
                $steamprofile['avatarmedium'] = $_SESSION['steam_avatarmedium'];
                $steamprofile['avatarfull'] = $_SESSION['steam_avatarfull'];
                $steamprofile['personastate'] = $_SESSION['steam_personastate'];
                $steamprofile['realname'] = $_SESSION['steam_realname'];
                $steamprofile['primaryclanid'] = $_SESSION['steam_primaryclanid'];
                $steamprofile['timecreated'] = $_SESSION['steam_timecreated'];
            }
        }
    }
?>

**Comment by Sphagnum** [comment]
Okay it was a allow_url_fopen = Off problem when calling file_get_contents().  Fixed by adding a php.ini with it set to on.  You should use the fixed logic though, so as to prevent the logout button (and the rest of the webpage along with it) from disappearing when file_get_contents() fails.

**Comment by BlackCetha** [comment]
No. You should not rely on the build-in functions as they kinda suck.
Build your own login/out button-logic.

**Comment by Sphagnum** [comment]
Yep, got it all working.  Side note, the $steamprofile[...] variables don't seem to be used anywhere.  I removed them completely without issue.  Thanks for the library!  All the other ones are atrocious by comparison.

**Comment by BlackCetha** [comment]
$steamprofile-variables are used for easier access. Close please.
