### ISSUE TITLE
Looking to get achievement data with SteamAuthentication

### ISSUE THREAD

**Issue by AwesomeTurtwig** [SmItH197/SteamAuthentication#73]
Hello everyone,

I am wondering if it is possible to use this tool to get Steam Achievement data. Achievement data can be found at the following location below. This is just an example for a single game. XXXXXX is the developer key.

http://api.steampowered.com/ISteamUserStats/GetUserStatsForGame/v0001/?appid=204300&key=XXXXXX&steamid=76561198031677651?xml=1

If the dev key is entered, you'll see my personal achievements and stats for this game. However, if my profile were private, I would not be able to pull achievement or statistical data. Is there any way around this using this tool? I know Steam Authentication normally can get you achievement info.

Thanks.

**Comment by BlackCetha** [comment]
Just use the SteamAPI yourself. The SteamID64 of the user is always available with `$_SESSION[“steamid“]`.

**Comment by SmItH197** [comment]
as far as I know there isn't a way to get private data, I scanned over the valve wiki, authentication only provides us with their steamid which is then used to make the api call. I might be wrong but to my knowledge the user has to be set to public.
