### ISSUE TITLE
use another userinfo

### ISSUE THREAD

**Issue by mTorkaman** [SmItH197/SteamAuthentication#74]
hello , thx for this plgin .
i want to use this web api : http://api.steampowered.com/IDOTA2Match_<ID>/GetTournamentPlayerStats/v1

can you make this for me ?

doc : https://wiki.teamfortress.com/wiki/WebAPI/GetTournamentPlayerStats

**Comment by BlackCetha** [comment]
This is a *library* for logins through Steam. You can make your own API-calls. The users SteamID64 is saved in `$_SESSION[“steamid“]`.

**Comment by SmItH197** [comment]
It shouldn't be too difficult, just modify the URL in userInfo.php and the variables to make the call to whatever you want.

**Comment by SmItH197** [comment]
This isn't really anything to do with the project and its been awhile since there has been a response so I'm closing it.
