### ISSUE TITLE
"Couldn't connect to host" #2

### ISSUE THREAD

**Issue by wolmain** [SmItH197/SteamAuthentication#76]
Hi, I have a problem, when I log to my website, I have a "Couldn't connect to host" but I can't change and that work in local. (I can't change of server)

thank you

**Comment by BlackCetha** [comment]
Do you maybe have a firewall or something that could block PHPs access to steampowered.com or api.steampowered.com?

**Comment by wolmain** [comment]
Yeah my firewall is activate but what port is used ?

**Comment by BlackCetha** [comment]
Port 80, also you might want to grant PHP(.exe) full access to incoming and outgoing connections.
Its pretty unusual for a webserver to have a firewall.

**Comment by wolmain** [comment]
I have disable all my firewall to try, and that work ! but for security I need to activate the firewall I will try with the https port.

**Comment by wolmain** [comment]
OK the problem is the https, the firewall need to accept it ! 
thanks guy !
