### ISSUE TITLE
Internal Server Error on rare occasions

### ISSUE THREAD

**Issue by RonMelkhior** [SmItH197/SteamAuthentication#77]
Sometimes after logging in from steam and while waiting to be redirected back to our website, it takes forever and then shows an internal server error, it happens rarely, what would you like me to provide so you can help me identify the issue?

I did some simple changes to the library, changing the style of the login and logout buttons, and setting the logout page to completely unset the session.

**Comment by SmItH197** [comment]
link?

**Comment by RonMelkhior** [comment]
https://staff.panda-community.com/

Notes:
It might take quite a few tries, to replicate this I had to ask a few people to try it with me and I tried multiple times.
Also, on successful logins it will log you out automatically since I did not add you to the whitelist, please add me on Steam so I can add you and we could possibly debug this.

http://steamcommunity.com/id/app1enerd

**Comment by BlackCetha** [comment]
- close -
