### ISSUE TITLE
Login page variable doesn't work.

### ISSUE THREAD

**Issue by Obilux** [SmItH197/SteamAuthentication#80]
Hi,I want to send users to checkfirstlogin.php But Variable didn't work.Login page variable doesnt in any page.

**Comment by BlackCetha** [comment]
You need to include the library before any other text output, for example right at the beginning of you code.

**Comment by Obilux** [comment]
Of course i included.I tried to say login page orientation doesn't work.

**Comment by BlackCetha** [comment]
Try settings the `loginpage` variable to `"/"`.

**Comment by Obilux** [comment]
@BlackCetha Still same i tried more locations.and i tried wrong locations but it not throw a exception.

**Comment by BlackCetha** [comment]
It's right here: https://github.com/SmItH197/SteamAuthentication/blob/master/steamauth/steamauth.php#L45

Try downloading a fresh copy from this repo.

**Comment by Obilux** [comment]
I'm using last version.My logout page is index.php and it work perfectly.But loginpage going to last page.

**Comment by SmItH197** [comment]
try changing `header('Location: '.$returnTo);` to `header('Location: '.$steamauth['loginpage']);`

**Comment by Obilux** [comment]
@SmItH197 Thank you for help.It work perfectly.

**Comment by SmItH197** [comment]
No problem, I will update the main repo with the change

**Comment by SmItH197** [comment]
@Obilux could you try using the latest [steamauth file](https://github.com/SmItH197/SteamAuthentication/blob/master/steamauth/steamauth.php)? Just replace that one file for me and see if it works? thanks :)

**Comment by Obilux** [comment]
@SmItH197 Okey I'm trying :)

**Comment by Obilux** [comment]
@SmItH197 It work perfectly without problems.

**Comment by SmItH197** [comment]
This has been fixed in v2.3.2

**Comment by Obilux** [comment]
@SmItH197 You're welcome.
