### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by ScriptKiddytm** [SmItH197/SteamAuthentication#82]
Hello,

i have installed this library together with the demo script but am getting the error: err_too_many_redirects. Also when i set the login page to another page on the site (not the index) if redirects me to the index immediately (no matter what i set in the settings)

Its also the first part from that tutorial that causes the error which is loading the function, so i am asking what is causing this problem and how i can fix this.

Thanks a lot!

**Comment by BlackCetha** [comment]
Make sure youre runnning the latest version. We had a bug wich may cause this error: https://github.com/SmItH197/SteamAuthentication/issues/80

There might be more broken in this section, so I cant exactly tell you whats wrong.
