### ISSUE TITLE
No OpenID Server Found

### ISSUE THREAD

**Issue by EnergyFall** [SmItH197/SteamAuthentication#83]
I have setup everything correctly but when i press the login button on steam it gives me this error:
* "No OpenID Server found at http://steamcommunity.com/openid/id/76561198131586617" (Feel free to add me!)

**Comment by BlackCetha** [comment]
Everything is sent correctly by steam even tho your link is messed up. Normally its just http://steamcommunity.com/openid/.
Make sure you dont have that domain overriden or blocked by your hosting provider.

**Comment by xMGxMods** [comment]
Same here :/

**Comment by SmItH197** [comment]
Could you try a fresh install of v3.0 and tell me if the issue persists? 

Thanks!

**Comment by EnergyFall** [comment]
Sorry for not replying but i have been busy.
And i have found the problem being the host i had :D
