### ISSUE TITLE
Suggestion: Rolling back to f47fc78056081d6a83d277ae447c5386dc0909fc

### ISSUE THREAD

**Issue by BlackCetha** [SmItH197/SteamAuthentication#84]
Since we were running in some major problems with redirection after we tried to implement $_GET-passthrough on login, it may be a good idea and save us alot of trouble if we just roll back to the previous commit. My suggestion would be commit f47fc78056081d6a83d277ae447c5386dc0909fc.
We would only need to carry over the "good" changes, for example the file_get_contents() mute.

I'd like to hear opinions about that.

**Comment by SmItH197** [comment]
Sorry I've let this project go to sh*t, I agree. That's v2.1.3 right?

**Comment by SmItH197** [comment]
Ok I have rolled back to that commit. I'm looking through all commits since and seeing what updates should be added.
