### ISSUE TITLE
mysql?

### ISSUE THREAD

**Issue by willwhitehouse** [SmItH197/SteamAuthentication#86]
pfttt... im new to web development and was wondering about the sql in this

**Comment by wortel538** [comment]
What is your exact question?
Op 10 dec. 2015 07:06 schreef "MaccyD (MrMenuMaker)" <
notifications@github.com>:

**Comment by willwhitehouse** [comment]
im wanting to store and load users information in a mysql table but im not sure how

**Comment by Gummibeer** [comment]
Just grab the infos, like in the `demo.php` and store them with the `mysqli()` functions in your database.

http://php.net/manual/de/book.mysqli.php

**Comment by jonathan148** [comment]
You can put in steamauth/steamauth.php line 38 the query stuff. line 38 will get executed on succesful login.

**Comment by BlackCetha** [comment]
You should only directly touch the library if you know what youre doing.

**Comment by bman46** [comment]
I found a article that would give you a good understanding of mySQL: http://www.w3schools.com/php/php_mysql_intro.asp (go thought all of the MySQL lessons and it should give you a excellent understanding of mySQL)

Code example (will need to be edited slightly and uses mySQLI):

`<?php
$servername = "localhost";
$username = "username";
$password = "password";
$dbname = "myDB";

// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);
// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
} 

$sql = "INSERT INTO Table (SteamName, ImageURLSmall)
VALUES ($steamprofile['personaname'], $steamprofile['avatar'])";

if ($conn->query($sql) === TRUE) {
    echo "New record created successfully";
} else {
    echo "Error: " . $sql . "<br>" . $conn->error;
}

$conn->close();
?> `

However i did not try this code so it may/may not work and it requires a bit more work to set up, so make sure you read the articles.

**Comment by BlackCetha** [comment]
Do not use the above code.

It will not work at all but at the same time opens up huge security holes.

Read http://php.net/manual/en/mysqli.real-escape-string.php

**Comment by bman46** [comment]
Yes, @blackcetha it has some problems with it, but It's meant for beginners and is very basic and not confusing to understand and as you learn more you can rewrite it to prevent from injections. So basically I would only use this for experimental reasons and to get a better understanding of the library.

**Comment by bman46** [comment]
@BlackCetha is this better?:

<?php

try {
    $handler = new PDO('mysql:host=localhost;dbname=s','root', '*');
    $handler->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch (PDOException $e){
    exit($e->getMessage());
}

$username = $steamprofile['personaname'];
$image = $steamprofile['avatarfull'];

$salt = md5(uniqid(null, true));

$sql = '
    INSERT INTO userinfo 
        (username, image, salt) 
    VALUES 
        (:username, :image, :salt)
';

$query = $handler->prepare($sql);

$query->execute(array(
    ':username' => $username,
    ':image' => $image,
    ':salt' => $salt
));
?> 

<strong> still, never tested it so don't know if it works and found code on internet (thq [stack exchange](http://codereview.stackexchange.com/questions/48095/preventing-sql-injection-in-user-registration-routine) )</strong>

**Comment by bman46** [comment]
Does salting make a difference @BlackCethia

**Comment by bman46** [comment]
Is it good? @BlackCetha

**Comment by BlackCetha** [comment]
PDO is overkill. While its not neccessarily bad, its just complicated.
If you use mysqli prepared statements, it should be alright.

**Comment by bman46** [comment]
Awesome Thq
