### ISSUE TITLE
 strpos(): Offset not contained in string in openid.php on line 84

### ISSUE THREAD

**Issue by RickyWoes** [SmItH197/SteamAuthentication#87]
I dont know what happened it was fine until i tried to make a img link then this happen i don't think i even opened the openid before this error nor have i changed the login function. 

 if(($host_end = strpos($this->trustRoot, '/', 8)) !== false) {
            $this->trustRoot = substr($this->trustRoot, 0, $host_end);
        }

that is line 84 I would love help if you can and I really love your work

**Comment by andrewda** [comment]
This occurs when the offset is larger than the string's length - 1. For example, if you have `strpos($this->trustRoot, '/', 8))`, `$this->trustRoot` must be at least 9 characters long. Above

```
if(($host_end = strpos($this->trustRoot, '/', 8)) !== false) {
```

write a line like `echo $this->trustRoot` to see how long the string is.

**Comment by RickyWoes** [comment]
Can I increase the limit or will that ruin everything

**Comment by RickyWoes** [comment]
also its only echoing http:// so i decreased it to 7 and the error went away but it still wont let me log in its says error every time i try to sign in

**Comment by RickyWoes** [comment]
I think it has something to do with the settings because on the loggin screen my website name does not popup

**Comment by RickyWoes** [comment]
As i try to figure this out it gets more weird the example.php works perfectly. and I using the exact same function to log in. Here is my site if it helps http://csgosalt.com/steamauth/example.php and my accual site that is in alpha http://csgosalt.com/

**Comment by BlackCetha** [comment]
You can basically see SteamAuth as dead. It's been buggy for a few month and the owner isn't going to fix it anytime soon.

**Comment by RickyWoes** [comment]
well it was working at first so this is disappointing. Do you know of any other authenticator that is good.

**Comment by SmItH197** [comment]
Sorry guys, I've been travelling around europe for a while. And I agree its
in a worry state. And with a full time job and training six days a week
I've had very little time to work on this. I'm going to roll back to an
older version and work from there.

**Comment by RickyWoes** [comment]
If i use the older version will it help my issue

**Comment by SmItH197** [comment]
could you post the code at the top of your index.php? It shows the logout buttons even though I haven't logged in.

**Comment by RickyWoes** [comment]
The only reason i did that was because i havent set up the if statement yet because i was focusing on a bot but ok.

**Comment by SmItH197** [comment]
Just tried your site again, it seems to be working fine?
