### ISSUE TITLE
problem with mysql

### ISSUE THREAD

**Issue by yolomaister** [SmItH197/SteamAuthentication#89]
hey,

If i dirrectly use my .php file (127.0.0.1//steamauth/db.php) what tells the database to store the datas of the steam account it stores them but if i try to login with my steam account on the main page it doesnt store anything in the database. 
This only works if i loggined in, if i use this when im not loggined it, it creates an empty line and gives a notice :
```
Notice: Undefined index: steamid in C:\xampp\htdocs\Steamauth\userInfo.php on line 4
Notice: Undefined offset: 0 in C:\xampp\htdocs\Steamauth\userInfo.php on line 6
Notice: Undefined offset: 0 in C:\xampp\htdocs\Steamauth\userInfo.php on line 7
Notice: Undefined offset: 0 in C:\xampp\htdocs\Steamauth\userInfo.php on line 8
Notice: Undefined offset: 0 in C:\xampp\htdocs\Steamauth\userInfo.php on line 9
Notice: Undefined offset: 0 in C:\xampp\htdocs\Steamauth\userInfo.php on line 10
Notice: Undefined offset: 0 in C:\xampp\htdocs\Steamauth\userInfo.php on line 11
Notice: Undefined offset: 0 in C:\xampp\htdocs\Steamauth\userInfo.php on line 12
Notice: Undefined offset: 0 in C:\xampp\htdocs\Steamauth\userInfo.php on line 13
Notice: Undefined offset: 0 in C:\xampp\htdocs\Steamauth\userInfo.php on line 14
Notice: Undefined offset: 0 in C:\xampp\htdocs\Steamauth\userInfo.php on line 15
Notice: Undefined offset: 0 in C:\xampp\htdocs\Steamauth\userInfo.php on line 21
Notice: Undefined offset: 0 in C:\xampp\htdocs\Steamauth\userInfo.php on line 22
Notice: Use of undefined constant mysqli_num_rows - assumed 'mysqli_num_rows' in C:\xampp\htdocs\Steamauth\db.php on line 24 <-- i know this im working on a fix, its not related to this repository at all.
```
Im using include 'db.php'; in steamauth/steamauth.php line 38. Tried to use it in other lines but it did not work either.

The db.php file:
```
<?php

//Connection
$dbhost = "127.0.0.1";
$dbuser = "root";
$dbpass = "";
$dberror1 = "Could not connect to our database!";
$dberror2 = "Could not find selected database!";

//Create connection
$conn = mysqli_connect($dbhost, $dbuser, $dbpass) or die ($dberror1);

//Select which database table we wish to connect to
$select_db = mysqli_select_db($conn, 'site') or die ($dberror2);

//Loading the needed files
require '../Steamauth/steamauth.php';
require '../Steamauth/userInfo.php';
$a=$steamprofile['steamid'];
$b=$steamprofile['personaname'];
$c=$steamprofile['avatar'];
$q="SELECT * FROM USER Where steamid='$a'";
$r=mysqli_query($conn,$q);
if (mysqli_num_rows > 0) {
    die ("User exists");
} 
else
{
//Storring the steam user infos in the database
$q="INSERT INTO user (steamid, personaname, avatar) VALUES('$a', '$b', '$c')";
mysqli_query($conn, $q);
}

?>
```
If any of you could help me with this I'd be thankful.

**Comment by BlackCetha** [comment]
You are not checking if the user is logged in and execute your query regardless.
If the user is not logged in, the `$steamprofile` variable is not set.
You can check if the user is logged in with `if (isset($_SESSION["steamid"]))`.

**Comment by yolomaister** [comment]
Almost everything works now but what i dont understand is what am i supposed to type in instead of "$player->steamid" and the others when im trying to insert them into the database, because i tried with foreach and every other way i could but it only puts empty lines into the database instead of actual datas.


                session_start();
                $_SESSION['steamid'] = $matches[1]; 
                
                require 'userInfo.php';
                
                //Mysql Connection
                $dbhost = "127.0.0.1";
                $dbuser = "root";
                $dbpass = "";
                $dberror1 = "Could not connect to our database!";
                $dberror2 = "Could not find selected database!";

                //Create connection
                $conn = mysqli_connect($dbhost, $dbuser, $dbpass) or die ($dberror1);

                //Select which database table we wish to connect to
                $select_db = mysqli_select_db($conn, 'site') or die ($dberror2);    
                
        
                $sql_fetch_id ="SELECT * FROM users WHERE steamid = $player->steamid";
                /* @var $query_id type */
                $query_id = mysqli_query($conn, $sql_fetch_id);
                    
                    if(mysqli_num_rows($query_id) == 0){
                    /* @var $sql_steam type */
                    $sql_steam = "INSERT INTO users (name, steamid, avatar, communityvisibilitystate, profilestate) VALUES ('$player->personaname', '$player->steamid', '$player->avatar', '$player->communityvisibilitystate', '$player->profilestate')";
                     mysqli_query($conn, $sql_steam);
                    }
                
                 if (isset($steamauth['loginpage'])) {
					header('Location: '.$steamauth['loginpage']);
                 }

**Comment by SmItH197** [comment]
Use the variables in the readme.
```$steamprofile['steamid']

**Comment by SmItH197** [comment]
Where are you declaring $player?

**Comment by BlackCetha** [comment]
Can we agree on closing issues with more that 30 days of inactivity or that are just general PHP questions after theyve been answered?
