### ISSUE TITLE
Could not resolve host: steamcommunity.com

### ISSUE THREAD

**Issue by naksuasd** [SmItH197/SteamAuthentication#90]
Suddenly this problem popped, after month of smooth use.
I have not changed anything.

When i call:
steamlogin();

I get this:
Could not resolve host: steamcommunity.com

**Comment by SmItH197** [comment]
If nothing on your end has Changed then its probably a problem with the steam servers. Try again later and see if you still have the same problem.

**Comment by SmItH197** [comment]
Do you have a link I can try?

**Comment by naksuasd** [comment]
Its have been whole day not working. And yeah, sure: http://csgobetshark.com

**Comment by naksuasd** [comment]
Tried it on my pc (localhost) and it works fine.

**Comment by SmItH197** [comment]
Googling the error, it seems to be a server issue. You can test it with a test file with something along the lines of:

```php
<?php

$web_content = file_get_contents("http://www.google.com/");

?>

```

**Comment by SmItH197** [comment]
Seems to be working now, likely a server issue.
