### ISSUE TITLE
Steamauthentication long error

### ISSUE THREAD

**Issue by sword134** [SmItH197/SteamAuthentication#92]
My friend has a server box that we use to host our website. Problem is that only he is able to login on the website, everytime i try to do i get i a long error that looks something like this.

http://mywebsite.com/?login&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fsteamcommunity.com%2Fopenid%2Flogin&openid.claimed_id=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198188112034&openid.identity=http%3A%2F%2Fsteamcommunity.com%2Fopenid%2Fid%2F76561198188112034&openid.return_to=http%3A%2F%2Fmywebsite.com%2F%3Flogin&openid.response_nonce=2016-01-01T14%3A43%3A20ZXeJ6R4sMTsgzT86etUKJe9BGlEc%3D&openid.assoc_handle=1234567890&openid.signed=signed%2Cop_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle&openid.sig=yPjLrR7LmloAHU64DeTdwPFlRaw%3D

**Comment by therustywolf** [comment]
Seems strange. Any solution on this?

**Comment by feelo112** [comment]
это довольно просто, чтобы просто закрыть окно сервера и запустить его снова, если это не работает, необходимо закрыть окно сервера в день, и это сфальсифицированы

**Comment by sword134** [comment]
English please?

**Comment by feelo112** [comment]
google tranlate

**Comment by sword134** [comment]
I tried restarting

**Comment by sword134** [comment]
It didnt work and it has been like this for days

**Comment by feelo112** [comment]
включить его вниз в течение дня

**Comment by feelo112** [comment]
my london not good

**Comment by sword134** [comment]
I have tried shutting off the server doesnt work. Only works for the localhost aka my friend

**Comment by wortel538** [comment]
Make sure you got SteamLogin(); on the page it's on.

2016-01-01 15:56 GMT+01:00 feelo112 <notifications@github.com>:

**Comment by sword134** [comment]
Guys try take a look at the site will try check for steamlogin in a sec. www.csgoeasyjackpot.com and try login it should give you the same code

**Comment by sword134** [comment]
SteamLogin(); didnt work

**Comment by sword134** [comment]
Any other ideas?

**Comment by BlackCetha** [comment]
It seems that your server is not able to handle the login function.
There is probably a syntax error in your code when the user is logged in.
Try putting `error_reporting(E_ALL);` on the very top of your index.php.

**Comment by sword134** [comment]
didnt seem to do anything?

<?php
@include_once "langdoc.php";
if(!isset($_COOKIE['lang'])) {
	setcookie("lang","en",2147485547);
	$lang = "en";
} else $lang = $_COOKIE["lang"];
$sitename = "CSGOEasyJackpot";
$title = "$sitename";
@include_once('set.php');
require('steamauth/steamauth.php');
	if(isset($_SESSION["steamid"])) {
include_once('steamauth/userInfo.php');}
error_reporting(E_ALL);
?>

**Comment by BlackCetha** [comment]
Because it is *not* at the top.

**Comment by sword134** [comment]
when i put it at the top it just becomes a text on the side of the website

**Comment by sword134** [comment]
https://gyazo.com/1592fb42f6af9d2d58e168f65216c621
https://gyazo.com/017d54c67493d3433c77f6d3cae6641b (Look up in left corner)

**Comment by sword134** [comment]
And even though it were to work. Where would i have to look for the error log?

**Comment by BlackCetha** [comment]
What you lack is a basic understanding of PHP.
You should not be in charge of running an app that deals with user data and where security is a concern.
I strongly advice you to first learn PHP and to maybe try again in two to three years.

**Comment by sword134** [comment]
well well, thats what i need to hear, thanks for the advice though. But you only get better when trying.

**Comment by sword134** [comment]
Still looking for a solution though

**Comment by sword134** [comment]
Still cant seem to fix it. Tried doing all of above none worked

**Comment by BlackCetha** [comment]
I'll help you to fix it even tho I'd still advice you to start with smaller projects (more importantly without dealing with money).

`error_reporting(E_ALL)` is obviously a PHP command. As one, it needs to be between your PHP-tags.
See if you get any error messages.

**Comment by sword134** [comment]
added a line like this to the index.php
Now where do i see the error messages?
<?php error_reporting(E_ALL) ?>

Later i tried using this

<?php
// Turn off error reporting
error_reporting(1);

// Report runtime errors
error_reporting(E_ERROR | E_WARNING | E_PARSE);

// Report all errors
error_reporting(E_ALL);

// Same as error_reporting(E_ALL);
ini_set("error_reporting", E_ALL);

// Report all errors except E_NOTICE
error_reporting(E_ALL & ~E_NOTICE);
?>

**Comment by sword134** [comment]
Any solution?

**Comment by SmItH197** [comment]
I get the below when I try your website:
http://m.imgur.com/a/90HH0

Suggests a DNS problem with your server, do you have any server error logs you can post?

**Comment by sword134** [comment]
if you look in the url you can see the error i posted in the start. A DNS error you said. I recently redirected my domain to a new host. That might be the issue and no i dont have any server error logs sadly :/

**Comment by SmItH197** [comment]
Have you tried setting `$steamauth['loginpage']` in settings.php on line 6 to index.php?

**Comment by sword134** [comment]
SmltH197 i checked the DNS no problems there. Checked the settings.php it was set to redirect to settings.php. Changed it to index.php didnt solve anything.

**Comment by SmItH197** [comment]
OK so I tried to login, and after login I got redirected here?

http://i.imgur.com/K9zji5D.png

**Comment by sword134** [comment]
i dont even get redirected to that? And that side is my friend (Who owns the server box) brothers project. Let me just sort it out

**Comment by sword134** [comment]
ok fixed it. Site works :D

**Comment by SmItH197** [comment]
Glad to hear it! :)
