### ISSUE TITLE
PHP Fatal error:  Maximum execution time of 30 seconds exceeded in openid.php on line 188

### ISSUE THREAD

**Issue by Frederik123** [SmItH197/SteamAuthentication#93]
Periodically in logs php there is such a mistake. - PHP Fatal error:  Maximum execution time of 30 seconds exceeded in ...openid.php on line 188

Any ideas how to fix?

**Comment by BlackCetha** [comment]
This is just the Steam OpenID-Server timing out.
While you could increase the execution time for openid.php, you shouldnt if it doesnt happen too often.
Your users will only see a PHP error wich will most likely make them go back and try logging in again.
