### ISSUE TITLE
SteamAuth with Slim Framework 

### ISSUE THREAD

**Issue by ImChip** [SmItH197/SteamAuthentication#94]
Hi 
i use this library for custom profile for my players 
if i not include this on my framework (slim-framework) its working
But if include on framework i got error with login he redirect on 404 not found
Any soluce ?

**Comment by SmItH197** [comment]
Change `$steamauth['loginpage']` to the page you want to login to.

**Comment by ImChip** [comment]
@SmItH197 
Ty for reply 
i cant see steam login page 
demo here 
https://www.homelife-roleplay.fr/test/index.php/profil

**Comment by SmItH197** [comment]
Where have you uploaded the steamauth folder?

**Comment by ImChip** [comment]
https://www.homelife-roleplay.fr/test/lib/steamauth/

**Comment by SmItH197** [comment]
Try moving it to /test/steamauth?

**Comment by ImChip** [comment]
i work on my localhost's server 
i upload then for you see my bug 
not working after moving steamauth in / i got same error
