### ISSUE TITLE
Great and perfect work. Question about Steam Guard Mobile Authenticator

### ISSUE THREAD

**Issue by AngelTsTsvetkov** [SmItH197/SteamAuthentication#98]
Is it possible programmatically via javascrpt or php to determine if some trader's trade link have enabled Steam Guard Mobile Authenticator?
Thanks for your good work and help.

**Comment by wortel538** [comment]
I know for sure that its possible with an external SteamBot

**Comment by AngelTsTsvetkov** [comment]
I am doing my research and for now I discover two js variables after loaded ".../tradeoffer/new/..."
var g_daysMyEscrow = 0;var g_daysTheirEscrow = 3;
This is the key of the shed :)

**Comment by AngelTsTsvetkov** [comment]
After I successful load demo.php ( successful log in my steam account) I can't load "https://steamcommunity.com/tradeoffer/new/?partner=89647317&token=vmYJwN-y" because its want from me to log again. Can you help?

**Comment by SmItH197** [comment]
I've not looked in to the grading APIs myself. But have you read: https://developer.valvesoftware.com/wiki/Steam_Web_API/IEconService

**Comment by bman46** [comment]
@AngelTsTsvetkov if u get it to work, plz post the code so we may be able to expand this code library

**Comment by RedSparr0w** [comment]
it doesn't look like there is anything in the [steam api](https://lab.xpaw.me/steam_api_documentation.html) for checking trading status, most likely would have to use a steam bot for this.

**Comment by bman46** [comment]
@redsparr0w apparently they got it to respond if they do have a escrow, but it requires a trade request
