### ISSUE TITLE
Doesnt work the logout button.

### ISSUE THREAD

**Issue by 4izburger** [SmItH197/SteamAuthentication#99]
I press logout, and nothing happens.
But the redirect to the 'logoutpage' works, at thebar it shows the adress
It is a problem of Session?
Or maybe the function does not work propelly?
Downloaded the latest version.

And when I reload the page, the session is still on

**Comment by 4izburger** [comment]
it work propelly on denwer. 
i am using modx, so i guess the problem is in it

any offers?

**Comment by SmItH197** [comment]
Do you have a link to your site?

**Comment by 4izburger** [comment]
moscoworiginal.ru

**Comment by 4izburger** [comment]
I solved the problem.
modx has its own class to work with sessions & cookies. 
One way to solve it - just turn of "session_handler_class" in the settings.
Second way - to use modx class.

**Comment by 4izburger** [comment]
Anyway, thx
